#ifndef __PROTOCOL_H__
#define __PROTOCOL_H__


/********************************************/
/*				CATEGORY					*/
/********************************************/
enum MP_CATEGORY
{
	MP_SERVER = 1,	// MP_SERVER￠￥A Ay￠￥e 0AI¨ui¨uⓒ￢CN￠￥U.
	MP_POWERUP,
	MP_CHAR,
	MP_MAP,
	MP_ITEM,
	MP_CHAT,
	MP_USERCONN,
	MP_MOVE,
	MP_SKILLTREE,
	MP_AUCTIONBOARD,
	MP_CHEAT,		// GMTOOL
	MP_QUICK,
	MP_PACKEDDATA,
	MP_PARTY,
	MP_PEACEWARMODE,
	MP_UNGIJOSIK,
	MP_AUCTION,
	MP_AUTOPATCH,	// pjs [4/27/2003]
	MP_SIGNAL,
	MP_MUNPA,
	MP_SKILL,
	MP_KYUNGGONG,
	MP_SIMBUB,
	MP_MORNITORTOOL,
	MP_MORNITORSERVER,
	MP_MORNITORMAPSERVER,
	MP_EXCHANGE,
	MP_STREETSTALL,
	MP_STORAGE,
	MP_BATTLE,
	MP_CHAR_REVIVE,
	MP_FRIEND,
	MP_BOSSMONSTER,
	MP_MONSTER,
	MP_OPTION,
	MP_NPC, // Npc￠?IAC ¡ioE¡I AU￠?e (￠￥eE¡ⓒⓒø¨￡ ¡ÆA¡¤￠® ￥ii￥ii) LBS 03.12.24
	MP_MURIMNET,
	MP_QUEST,		// ￠￢OAu QuestAC ¡ioAA¡Æ¨￡ AuAa ¡¤c¨¡¨u￠￢￠￢ ￠￢￠￢￥ic￠￥U. LBS 04.01.06
	MP_DEBUG,
	MP_PK,	//PK
	MP_HACKCHECK,
	MP_RMTOOL_CONNECT,
	MP_RMTOOL_USER,
	MP_RMTOOL_MUNPA,
	MP_RMTOOL_GAMELOG,
	MP_RMTOOL_OPERLOG,
	MP_RMTOOL_STATISTICS,
	MP_RMTOOL_ADMIN,
	MP_RMTOOL_CHARACTER, 
	MP_RMTOOL_ITEM,
	
	/////////////////////
	MP_WANTED,
	MP_JOURNAL,
	MP_SURYUN,
	MP_SOCIETYACT,
	MP_GUILD,
	MP_GUILD_WAR,
	MP_NOTE,
	MP_PARTYWAR,
	MP_GTOURNAMENT,
	MP_JACKPOT,
	MP_GUILD_UNION,
	MP_SIEGEWAR,
	MP_SIEGEWAR_PROFIT,
	MP_WEATHER,
	MP_HACKSHIELD,
	MP_NPROTECT,
	MP_RMTOOL_DELCHAR,
	MP_FAMILY,
	MP_FACIAL,
	MP_EMOTION,
	MP_DATEMATCHING,
	MP_DATE,
	MP_FARM,
	MP_RESIDENTREGIST,
	MP_TUTORIAL,
	MP_MARRIAGE,
	MP_AUTONOTE,
	MP_PUNISH,
	MP_CHATROOM,
	MP_FISHING,
	MP_PET,
  	MP_SIEGERECALL,
	MP_SIEGEWARFARE,
	MP_RECALLNPC,
	MP_COOK,
	MP_LIMITDUNGEON,
	MP_VEHICLE,
	MP_HOUSE,
	MP_TRIGGER,
	MP_DUNGEON,
	MP_PCROOM,
	MP_CONSIGNMENT,
	MP_MAX,
};
 
/********************************************/
/*		PROTOCOL LEVEL 2					*/
/********************************************/
enum MP_PROTOCOL_NPROTECT
{
	MP_NPROTECT_QUERY,
	MP_NPROTECT_ANSWER,
	MP_NPROTECT_DISCONNECT,
	MP_NPROTECT_USER_DISCONNECT,
};

enum MP_PROTOCOL_HACKSHIELD
{
	MP_HACKSHIELD_GUID_REQ,
	MP_HACKSHIELD_GUID_ACK,
	MP_HACKSHIELD_REQ,
	MP_HACKSHIELD_ACK,
	MP_HACKSHIELD_DISCONNECT,
};

enum MP_PROTOCOL_MORNITORTOOL // MAPTOOL_CLIENT ￠?I MAPSERVER¡Æ¡IAC CwIAaAY
{
	MP_MORNITORTOOL_EXECUTE_MAPSERVER_SYN,
	MP_MORNITORTOOL_EXECUTE_MAPSERVER_ACK,/*not used*/
	MP_MORNITORTOOL_EXECUTE_MAPSERVER_NACK,/*not used*/

	MP_MORNITORTOOL_SHUTDOWN_MAPSERVER_SYN,
	MP_MORNITORTOOL_SHUTDOWN_MAPSERVER_ACK,/*not used*/
	MP_MORNITORTOOL_SHUTDOWN_MAPSERVER_NACK,/*not used*/
	
	MP_MORNITORTOOL_NOTICESEND_SYN,
	MP_MORNITORTOOL_NOTICESEND_ACK,/*not used*/
	MP_MORNITORTOOL_NOTICESEND_NACK,/*not used*/

	MP_MORNITORTOOL_MAPSERVERSTATE_SYN,				// ¡ioAA ￠?aA¡i 
	MP_MORNITORTOOL_MAPSERVERSTATE_ACK,
	MP_MORNITORTOOL_MAPSERVERSTATE_NACK,

	MP_MORNITORTOOL_MAPSERVERSTATE_NOTIFY,

	MP_MORNITORTOOL_EXECUTE_AUTOPATCH_SYN,			// AutoPatch
	MP_MORNITORTOOL_CHANGE_USERLEVEL_SYN,			// UserLevel
	MP_MORNITORTOOL_CHANGE_USERLEVEL_ACK,
	MP_MORNITORTOOL_CHANGE_USERLEVEL_NACK,
	
	MP_MORNITORTOOL_QUERYUSERCOUNT_SYN,
	MP_MORNITORTOOL_QUERYUSERCOUNT_ACK,
	MP_MORNITORTOOL_QUERYUSERCOUNT_NACK,
	
	MP_MORNITORTOOL_ASSERTMSGBOX_SYN,

	MP_MORNITORTOOL_DISCONNECT_ALLUSER_SYN,		
	MP_MORNITORTOOL_DISCONNECT_ALLUSER_ACK,
	MP_MORNITORTOOL_DISCONNECT_ALLUSER_NACK,

	MP_MORNITORTOOL_QUERY_VERSION_SYN,			// version
	MP_MORNITORTOOL_QUERY_VERSION_ACK,
	MP_MORNITORTOOL_QUERY_VERSION_NACK,

	MP_MORNITORTOOL_CHANGE_VERSION_SYN,
	MP_MORNITORTOOL_CHANGE_VERSION_ACK,
	MP_MORNITORTOOL_CHANGE_VERSION_NACK,
	
	MP_MORNITORTOOL_QUERY_MAXUSER_SYN,
	MP_MORNITORTOOL_QUERY_MAXUSER_ACK,

	MP_MORNITORTOOL_CHANGE_MAXUSER_SYN,
	MP_MORNITORTOOL_CHANGE_MAXUSER_ACK,
	
	MP_MORNITORTOOL_MSSTATEALL_SYN,
	MP_MORNITORTOOL_MSSTATEALL_ACK,

	MP_MORNITORTOOL_CHECK_AUTOPATCH_ACK,
	MP_MORNITORTOOL_QUERY_AUTOPATCHVERSION_SYN,
	MP_MORNITORTOOL_QUERY_AUTOPATCHVERSION_ACK,
	
	MP_MORNITORTOOL_QUERY_CHANNELINFO_SYN,
	MP_MORNITORTOOL_QUERY_CHANNELINFO_ACK,
	
	MP_MORNITORTOOL_KILL_SERVER_SYN,

	MP_MORNITORTOOL_CONNECTED_SERVERLIST_SYN,
	MP_MORNITORTOOL_CONNECTED_SERVERLIST_ACK,
	
	MP_MORNITORTOOL_EVENTNOTICE_ON,
	MP_MORNITORTOOL_EVENTNOTICE_OFF,
	// 090511 LUJ, 권한 부족
	MP_MORNITORTOOL_NO_AUTHORITY_ACK,
};

enum MP_PROTOCOL_MORNITORSERVER
{
	MP_MORNITORSERVER_MSINFO_NOTIFY,
	MP_MORNITORSERVER_BOOTUP_NOTIFY,
	MP_MORNITORSERVER_BOOTLIST_NOTIFY,
	MP_MORNITORSERVER_EXECUTE_MAPSERVER_SYN,/*¨￢￠￢ⓒø¡i¡¾a￠￢￠￢ CI¡Æi ⓒo¨­Ao￠￥A ¨uE￠￥A￠￥U. */
	MP_MORNITORSERVER_EXECUTE_MAPSERVER_ACK,/*not used*/
	MP_MORNITORSERVER_EXECUTE_MAPSERVER_NACK,/*not used*/

	MP_MORNITORSERVER_SHUTDOWN_MAPSERVER_SYN,
	MP_MORNITORSERVER_SHUTDOWN_MAPSERVER_ACK,/*not used*/
	MP_MORNITORSERVER_SHUTDOWN_MAPSERVER_NACK,/*not used*/

	MP_MORNITORSERVER_NOTICESEND_SYN,
	MP_MORNITORSERVER_NOTICESEND_ACK,/*not used*/
	MP_MORNITORSERVER_NOTICESEND_NACK,/*not used*/

	MP_MORNITORSERVER_MAPSERVERSTATE_SYN,/*not used*/
	MP_MORNITORSERVER_MAPSERVERSTATE_ACK,/*ms->mas!!!!!!!!!!!*/
	MP_MORNITORSERVER_MAPSERVERSTATE_NACK,/*not used*/

	MP_MORNITORSERVER_EXECUTE_AUTOPATCH_SYN,	// AutoPatch
	MP_MORNITORSERVER_CHANGE_USERLEVEL_SYN,		// UserLevel
	MP_MORNITORSERVER_CHANGE_USERLEVEL_ACK,
	MP_MORNITORSERVER_CHANGE_USERLEVEL_NACK,
	
	MP_MORNITORSERVER_QUERYUSERCOUNT_SYN,
	MP_MORNITORSERVER_QUERYUSERCOUNT_ACK,
	MP_MORNITORSERVER_QUERYUSERCOUNT_NACK,
	
	MP_MORNITORSERVER_ASSERTMSGBOX_SYN,

	MP_MORNITORSERVER_DISCONNECT_ALLUSER_SYN,		
	MP_MORNITORSERVER_DISCONNECT_ALLUSER_ACK,
	MP_MORNITORSERVER_DISCONNECT_ALLUSER_NACK,

	MP_MORNITORSERVER_QUERY_VERSION_SYN,
	MP_MORNITORSERVER_QUERY_VERSION_ACK,
	MP_MORNITORSERVER_QUERY_VERSION_NACK,

	MP_MORNITORSERVER_CHANGE_VERSION_SYN,
	MP_MORNITORSERVER_CHANGE_VERSION_ACK,
	MP_MORNITORSERVER_CHANGE_VERSION_NACK,

	MP_MORNITORSERVER_QUERY_MAXUSER_SYN,
	MP_MORNITORSERVER_QUERY_MAXUSER_ACK,

	MP_MORNITORSERVER_CHANGE_MAXUSER_SYN,
	MP_MORNITORSERVER_CHANGE_MAXUSER_ACK,

	MP_MORNITORSERVER_CHECK_AUTOPATCH_ACK,
	MP_MORNITORSERVER_QUERY_AUTOPATCHVERSION_SYN,
	MP_MORNITORSERVER_QUERY_AUTOPATCHVERSION_ACK,

	MP_MORNITORSERVER_QUERY_CHANNELINFO_SYN,
	MP_MORNITORSERVER_QUERY_CHANNELINFO_ACK,

	MP_MORNITORSERVER_KILL_SERVER_SYN,

	MP_MORNITORSERVER_CONNECTED_SERVERLIST_SYN,
	MP_MORNITORSERVER_CONNECTED_SERVERLIST_ACK,

	MP_MORNITORSERVER_EVENTNOTICE_ON,
	MP_MORNITORSERVER_EVENTNOTICE_OFF,
};

enum MP_PROTOCOL_MORNITORMAPSERVER
{
	MP_MORNITORMAPSERVER_BOOTUP_NOTIFY,
	MP_MORNITORMAPSERVER_BOOTLIST_NOTIFY,
	MP_MORNITORMAPSERVER_EXECUTE_MAPSERVER_SYN,/*not used*/
	MP_MORNITORMAPSERVER_EXECUTE_MAPSERVER_ACK,/*not used*/
	MP_MORNITORMAPSERVER_EXECUTE_MAPSERVER_NACK,/*not used*/

	MP_MORNITORMAPSERVER_SHUTDOWN_MAPSERVER_SYN,/*not used*/
	MP_MORNITORMAPSERVER_SHUTDOWN_MAPSERVER_ACK,/*not used*/
	MP_MORNITORMAPSERVER_SHUTDOWN_MAPSERVER_NACK,/*not used*/

	MP_MORNITORMAPSERVER_NOTICESEND_SYN,
	MP_MORNITORMAPSERVER_NOTICESEND_ACK,/*not used*/
	MP_MORNITORMAPSERVER_NOTICESEND_NACK,/*not used*/

	MP_MORNITORMAPSERVER_PING_SYN,
	MP_MORNITORMAPSERVER_PING_ACK,

	MP_MORNITORMAPSERVER_CHANGE_USERLEVEL_SYN,
	MP_MORNITORMAPSERVER_CHANGE_USERLEVEL_ACK,
	MP_MORNITORMAPSERVER_CHANGE_USERLEVEL_NACK,

	MP_MORNITORMAPSERVER_QUERYUSERCOUNT_SYN,
	MP_MORNITORMAPSERVER_QUERYUSERCOUNT_ACK,
	MP_MORNITORMAPSERVER_QUERYUSERCOUNT_NACK,

	MP_MORNITORMAPSERVER_ASSERTMSGBOX_SYN,
	
	MP_MORNITORMAPSERVER_DISCONNECT_ALLUSER_SYN, /* ￠￢ⓒ￡￥ic /AuAC b¨uO; ~¡¤aCN￠￥U.*/
	MP_MORNITORMAPSERVER_DISCONNECT_ALLUSER_ACK,
	MP_MORNITORMAPSERVER_DISCONNECT_ALLUSER_NACK,

	MP_MORNITORMAPSERVER_SERVEROFF_SYN, /* ¨u¡ⓒⓒoo￠￢| Off¨oAAⓒ÷￠￥U.*/

	MP_MORNITORMAPSERVER_QUERY_VERSION_SYN,
	MP_MORNITORMAPSERVER_QUERY_VERSION_ACK,
	MP_MORNITORMAPSERVER_QUERY_VERSION_NACK,

	MP_MORNITORMAPSERVER_CHANGE_VERSION_SYN,
	MP_MORNITORMAPSERVER_CHANGE_VERSION_ACK,
	MP_MORNITORMAPSERVER_CHANGE_VERSION_NACK,

	MP_MORNITORMAPSERVER_QUERY_MAXUSER_SYN,
	MP_MORNITORMAPSERVER_QUERY_MAXUSER_ACK,

	MP_MORNITORMAPSERVER_CHANGE_MAXUSER_SYN,
	MP_MORNITORMAPSERVER_CHANGE_MAXUSER_ACK,

	MP_MORNITORMAPSERVER_QUERY_CHANNELINFO_SYN,
	MP_MORNITORMAPSERVER_QUERY_CHANNELINFO_ACK, 

	MP_MORNITORMAPSERVER_KILL_SERVER_SYN,			// not use

	MP_MORNITORMAPSERVER_CONNECTED_SERVERLIST_SYN,
	MP_MORNITORMAPSERVER_CONNECTED_SERVERLIST_ACK,	

	MP_MORNITORMAPSERVER_EVENTNOTICE_ON,
	MP_MORNITORMAPSERVER_EVENTNOTICE_OFF,
};

enum MP_PROTOCOL_SERVER
{
	// MP_SERVER
	MP_SERVER_PWRUP,
	MP_SERVER_MSG,
	MP_SERVER_USERCNT,

	MP_SERVER_CONNECT_SUCCESS,
	MP_SERVER_REGISTMAP_SYN,
	MP_SERVER_REGISTMAP_ACK,

	MP_SERVER_AGENTDISABLE,
	
	MP_SERVER_TEST_PROTOCOL,
};
enum MP_PROTOCOL_POWERUP
{
	//ms : ￠￢ⓒ￡￠￥IAI ¨u¡ⓒⓒoo, mas : ￠￢ⓒ￡￠￥IAI ￠?￠®AIAu¨¡￠c ¨u¡ⓒⓒoo
	MP_POWERUP_BOOTING_NOTIFY,		// ¨￢I¨¡A￥iE￠O¡× map->ms(->mas) 
	MP_POWERUP_BOOTLIST_SYN,		// map->ms(->mas)
	MP_POWERUP_BOOTLIST_ACK,		// (mas->)ms->map
	MP_POWERUP_CONNECT_SYN,			//
	MP_POWERUP_CONNECT_ACK,
};
//-------- Aⓒø￠￢?AI ¨uoA￠® d¨￢￠￢ CwIAaAY -----------------
enum MP_PROTOCOL_CHAR
{
	// MP_CHAR
	MP_CHAR_LIFE_SYN,				// ¡iy￠￢i¡¤A
	MP_CHAR_LIFE_ACK,
	MP_CHAR_LIFE_NACK,
	MP_CHAR_MAXLIFE_NOTIFY,

	MP_CHAR_MANA_SYN,			// ⓒø¡i¡¤A
	MP_CHAR_MANA_ACK,
	MP_CHAR_MANA_NACK,
	MP_CHAR_MAXMANA_NOTIFY,

	MP_CHAR_EXPPOINT_SYN,			// ¡Æⓒ¡CeA￠®
	MP_CHAR_EXPPOINT_ACK,
	MP_CHAR_EXPPOINT_NACK,

	MP_CHAR_STR_NOTIFY,
	MP_CHAR_DEX_NOTIFY,
	MP_CHAR_WIS_NOTIFY,
	MP_CHAR_VIT_NOTIFY,
	// 070411 LYW --- Protocon : Add protocon of intelligence part.
	MP_CHAR_INT_NOTIFY,


	MP_CHAR_LEVEL_NOTIFY,
	MP_CHAR_POINTADD_SYN,
	MP_CHAR_POINTADD_ACK,
	MP_CHAR_POINTADD_NACK,
	
	MP_CHAR_LEVELUPPOINT_NOTIFY,
	MP_CHAR_STATE_NOTIFY,

	MP_CHAR_LIFE_NOTIFY,	
	
	MP_CHAR_YOUAREDIED,
	
	MP_CHAR_EXITSTART_SYN,
	MP_CHAR_EXITSTART_ACK,
	MP_CHAR_EXITSTART_NACK,

	MP_CHAR_EXIT_SYN,
	MP_CHAR_EXIT_ACK,
	MP_CHAR_EXIT_NACK,

	MP_CHAR_BADFAME_NOTIFY,
	// 070412 LYW --- Protocol : Add protocol for change stage part.
	MP_CHAR_STAGE_NOTIFY,

	// desc_hseos_몬스터미터01
	// S 몬스터미터 추가 added by hseos 2007.05.23
	MP_CHAR_MONSTERMETER_KILLMONSTER,
	MP_CHAR_MONSTERMETER_PLAYTIME,
	// E 몬스터미터 추가 added by hseos 2007.05.23

	MP_CHAR_HIDE_NOTIFY,
	MP_CHAR_DETECT_NOTIFY,

	MP_CHAR_EMERGENCY_SYN,
	// 080616 LUJ, 플레이어의 최신 HP값을 서버에 요청한다. 5차 스킬 추가로 인해 스킬 발동 후 HP값을 변경하는 처리가 
	//				추가되었다. 그런데 클라이언트는 이펙트 처리 후 HP를 가감하기 때문에, 서버와 HP 값이 다른 경우가
	//				발생한다. 이를 보정하기 위해, 데미지가 있는 스킬은 처리 후 서버에 HP 값을 요청한다
	MP_CHAR_LIFE_GET_SYN,
	MP_CHAR_LIFE_GET_ACK,

	// 100223 ShinJS --- 마나데미지 추가로 인한 마나 정보 요청 프로토콜 추가
	MP_CHAR_MANA_GET_SYN,
	MP_CHAR_MANA_GET_ACK,

	MP_CHAR_LIFE_BROADCAST,
};
//-------- ¨uoA￠® d¨￢￠￢ CwIAaAY -----------------

enum MP_PROTOCOL_USERCONN
{
	MP_USERCONN_DIST_CONNECTSUCCESS,
	MP_USERCONN_LOGIN_SYN,
	MP_USERCONN_LOGIN_ACK,
	MP_USERCONN_LOGIN_NACK,
	MP_USERCONN_NOTIFY_USERLOGIN_SYN,
	MP_USERCONN_NOTIFY_USERLOGIN_ACK,
	MP_USERCONN_NOTIFY_USERLOGIN_NACK,
	MP_USERCONN_NOTIFY_OVERLAPPEDLOGIN,
	MP_USERCONN_AGENT_CONNECTSUCCESS,
	MP_USERCONN_USER_SEXKIND,
	MP_USERCONN_CHARACTERLIST_SYN,
	MP_USERCONN_DIRECTCHARACTERLIST_SYN,
	MP_USERCONN_CHARACTERLIST_ACK,
	MP_USERCONN_CHARACTERLIST_NACK,	
	
	MP_USERCONN_DISCONNECT_SYN,						// ¨u¡¾AAA¡E￠?￠®¨u¡ⓒ ¡¤I¡¾¡¿¨u¨¡￠?o ￠￥¡ⓒ¡¤￠O;￠O¡×
	MP_USERCONN_DISCONNECT_ACK,
	MP_USERCONN_DISCONNECT_NACK,

	MP_USERCONN_CHARACTERSELECT_SYN,				// Aⓒø￠￢?AI ¨u¡¾AA
	MP_USERCONN_CHARACTERSELECT_ACK,				// Aⓒø￠￢?AI ￠￢ⓒ￡￥icd¨￢￠￢(CHARACTER_TOTALINFO)￠￢| ⓒo¨­￠￥A protocol
	MP_USERCONN_CHARACTERSELECT_NACK,

	MP_USERCONN_CHARACTER_NAMECHECK_SYN,			// Aⓒø￠￢?AI AI￠￢¡×A¨uA¨I
	MP_USERCONN_CHARACTER_NAMECHECK_ACK,
	MP_USERCONN_CHARACTER_NAMECHECK_NACK,

	MP_USERCONN_CHARACTER_MAKE_SYN,					// Aⓒø￠￢?AI ￠￢￠￢￥ie¡¾a
	MP_USERCONN_CHARACTER_MAKE_ACK,					//¨uE¨u￠￢ Ao￠?o¨uⓒ￢Ao. HS
	MP_USERCONN_CHARACTER_MAKE_NACK,

	MP_USERCONN_CHARACTER_INFO_SYN,					//A￠￥￠￢?AI ￠￢￠￢￥ie¡¾a￠?￠®¨u¡ⓒ ¡io¡¤I Aⓒ￢¡Æ￠®CN protocol;
	MP_USERCONN_CHARACTER_INFO_ACK,
	MP_USERCONN_CHARACTER_INFO_NACK,

	MP_USERCONN_GAMEIN_SYN,						// ¡ÆOAO￠￢E￠?￠® b¨uO
	MP_USERCONN_GAMEIN_ACK,
	MP_USERCONN_GAMEIN_NACK,

	MP_USERCONN_GAMEOUT_SYN,						// ¡ÆOAO￠￢E￠?￠®¨u¡ⓒ ⓒø¨￡¡Æ¡§
	MP_USERCONN_GAMEOUT_ACK,
	MP_USERCONN_GAMEOUT_NACK,

	MP_USERCONN_DISCONNECTED,		// client￠?￠®¨u¡ⓒ ~¡¤aCO￠O¡×￠?I Agent￠?￠®¨u¡ⓒ b¨uOAI ⓒ÷¡A¡Æa;¡Æⓒ¡￠?i b¨uO￥iC¨uiAO￠￥ⓒª ￠￢E¨u¡ⓒⓒoo￠?￠® ¨uE¡¤AAU
	
	MP_USERCONN_CHARACTER_ADD,
	MP_USERCONN_MONSTER_ADD,
	MP_USERCONN_BOSSMONSTER_ADD, 
	MP_USERCONN_NPC_ADD,
	MP_USERCONN_OBJECT_REMOVE,
	MP_USERCONN_PET_ADD,
	MP_USERCONN_HEROPET_REMOVE,		
	// 090316 LUJ, 탈것
	MP_USERCONN_VEHICLE_ADD,
	MP_USERCONN_VEHICLE_REMOVE,

	MP_USERCONN_CHARACTER_DIE,			// CA¡¤ⓒoAI¨ui¡Æ￠® A¡¿¨uu;￠O¡×AC Aⓒø￠￢￠c
	MP_USERCONN_MONSTER_DIE,			// ￠￢o¨o¨￢AI¡Æ￠® A¡¿¨uu;￠O¡×AC Aⓒø￠￢￠c

	// 091110 ONS 펫 애니메이션 추가 : 죽음 애니메이션
	MP_USERCONN_PET_DIE,

	// 080402 NYJ - Test
	MP_USERCONN_NPC_ADD_SYN,
	MP_USERCONN_NPC_DIE_SYN,
	MP_USERCONN_NPC_DIE,

	// 070418 LYW --- Protocol : Add protocol to notice that down exp and level to client.
	MP_USERCONN_CHARACTER_APPLYEXP_NOTICE,
	MP_USERCONN_CHARACTER_DOWNEXP_NOTICE,
	MP_USERCONN_CHARACTER_DOWNLEVEL_NOTICE,

	MP_USERCONN_CHARACTER_REVIVE,
 
	MP_USERCONN_CHARACTER_REMOVE_SYN,		// AE￠￢?AI ¨u¡¾AAA¡E￠?￠®¨u¡ⓒ AE￠￢?AI Ao￠?i￠O¡×
	MP_USERCONN_CHARACTER_REMOVE_ACK,
	MP_USERCONN_CHARACTER_REMOVE_NACK,

	MP_USERCONN_CHANGEMAP_SYN,			// ￠￢E A¨uAIAo
	MP_USERCONN_CHANGEMAP_ACK,
	MP_USERCONN_CHANGEMAP_NACK,
	MP_USERCONN_MAP_OUT,
	MP_USERCONN_MAP_OUT_WITHMAPNUM,
	// 090512 ONS 타종족의 신규종족 시작맵으로의 이동 제한
	MP_USERCONN_DEVILMARKET_CHANGEMAP_NACK,

	// 081010 LYW --- Protocol : 공성전에서 사용할 맵이동 프로토콜 추가.
	MP_USERCONN_SIEGEWARFARE_MAP_OUT_WITHMAPNUM_SYN,
	MP_USERCONN_SIEGEWARFARE_MAP_OUT_WITHMAPNUM_ACK,
	MP_USERCONN_SIEGEWARFARE_MAP_OUT_WITHMAPNUM_NACK,

	MP_USERCONN_CHARACTER_TOTALINFO,

	MP_USERCONN_SAVEPOINT_SYN,			// ¡¤I¡¾a¨¡¡AAI¨¡￠c AuAa
	MP_USERCONN_SAVEPOINT_ACK,			
	MP_USERCONN_SAVEPOINT_NACK,
	
	MP_USERCONN_BACKTOCHARSEL_SYN,
	MP_USERCONN_BACKTOCHARSEL_ACK,
	MP_USERCONN_BACKTOCHARSEL_NACK,
	MP_USERCONN_GRIDINIT,
	
	MP_USERCONN_SETVISIBLE,
	MP_USERCONN_OTHERUSER_CONNECTTRY_NOTIFY,
	
	MP_USERCONN_CONNECTION_CHECK,		// A->C	￠?¡þ¡ÆaE￠cAI ￠￢¨­¨u¨uAo
	MP_USERCONN_CONNECTION_CHECK_OK,	// C->A A4a ￠￢¨­¨u¨uAo
	
	MP_USERCONN_CHECKSUMERROR,
	
	MP_USERCONN_FORCE_DISCONNECT_OVERLAPLOGIN,
	MP_USERCONN_DISCONNECTED_BY_OVERLAPLOGIN,
	
	MP_USERCONN_CHANNELINFO_SYN,
	MP_USERCONN_CHANNELINFO_ACK,
	MP_USERCONN_CHANNELINFO_NACK,
	MP_USERCONN_NOTIFYTOAGENT_ALREADYOUT,
	MP_USERCONN_REQUEST_DISTOUT,
	MP_USERCONN_DISCONNECTED_ON_LOGIN,
	MP_USERCONN_SERVER_NOTREADY,
	MP_USERCONN_MAPDESC,
	MP_USERCONN_CHARACTER_REVIVE_NACK,
	MP_USERCONN_CHARACTER_REVIVE_FLAG_ACK,
	MP_USERCONN_READY_TO_REVIVE,
	
	MP_USERCONN_CHEAT_USING,
	
	MP_USERCONN_CHEAT_CHANGEMAP_ACK,	//gmAI A¡Æ®·I ¸EAIμ¿CI°A³ª ½AA´

	MP_USERCONN_USE_DYNAMIC_SYN,							// ¨u¨¡AI￥iⓒ￡ ¨¡¨￠¨o¨￢￠?o￥ia ¡ÆE¡icⓒo¡¿ ¡¾aA￠￢ ￥ii￥ii ¡ÆE¡ic￠￢| Au¨￢I ￠?¨I¡¾a¨u¡ⓒ CN￠￥U.
	MP_USERCONN_USE_DYNAMIC_ACK,							// b¨uO ¨u¨￢¡ÆⓒªCI￠￢e Agent ¨u¡ⓒⓒoo ¨u¨¡AICC￠?I UserIdx,AuthKey￠￢| ⓒo¨­¨u¨¡￠?A￠￥U.
	MP_USERCONN_USE_DYNAMIC_NACK,

	MP_USERCONN_LOGIN_DYNAMIC_SYN,							// ¨u¨¡AI￥iⓒ￡ ¨¡¨￠¨o¨￢￠?o￥ia ¡ÆE¡icⓒo¡¿ ¡¾aA￠￢ ￥ii￥ii ¡ÆE¡ic￠￢| Au¨￢I ￠?¨I¡¾a¨u¡ⓒ CN￠￥U.
	MP_USERCONN_LOGIN_DYNAMIC_ACK,							// b¨uO ¨u¨￢¡ÆⓒªCI￠￢e Agent ¨u¡ⓒⓒoo ¨u¨¡AICC￠?I UserIdx,AuthKey￠￢| ⓒo¨­¨u¨¡￠?A￠￥U.
	MP_USERCONN_LOGIN_DYNAMIC_NACK,

	MP_USERCONN_LOGINCHECK_DELETE,
	MP_USERCONN_FORCE_DISCONNECT_OVERLAPLOGIN_ACK,

	MP_USERCONN_MAP_OUT_TO_EVENTMAP,	// eventmap
	MP_USERCONN_MAP_OUT_TO_EVENTBEFOREMAP,
	MP_USERCONN_ENTER_EVENTMAP_SYN,	
	MP_USERCONN_EVENT_READY,
	MP_USERCONN_EVENT_START,	
	MP_USERCONN_EVENT_END,

	MP_USERCONN_EVENTITEM_USE,			//050106 event
	MP_USERCONN_EVENTITEM_USE2,

	MP_USERCONN_GAMEINPOS_SYN,
	MP_USERCONN_GAMEINPOS_ACK,
	MP_USERCONN_GAMEINPOS_NACK,

	MP_USERCONN_ENTER_GTOURNAMENT_SYN,
	
	MP_USERCONN_CHARACTERSLOT,	
	MP_USERCONN_GAMEIN_OTHERMAP_SYN,	//현재106.. 128넘으면 안되지 않남?
	MP_USERCONN_NOWAITEXITPLAYER,

	MP_USERCONN_READY_TO_REVIVE_BY_GFW,	// 길드전으로 사망한 경우에는 일반 사망과는 다른 처리가 필요하다

	MP_USERCONN_RETURN_SYN,
	MP_USERCONN_RETURN_ACK,
	MP_USERCONN_RETURN_NACK,

	// 070917 LYW --- Protocol : Add protocol to process change map through the npc.
	MP_USERCONN_NPC_CHANGEMAP_SYN,
	MP_USERCONN_NPC_CHANGEMAP_ACK,
	MP_USERCONN_NPC_CHANGEMAP_NACK,
	MP_USERCONN_NPC_MAP_OUT,
	// 100302 ONS 퀘스트를 통한 맵이동 프로토콜 추가.
	MP_USERCONN_QUEST_CHANGEMAP_SYN,
	// 071226 KTH --
	MP_USERCONN_MEMORY_MAP_SYN,
	MP_USERCONN_MEMORY_MAP_ACK,
	MP_USERCONN_MEMORY_MAP_NACK,
	// 081031 LUJ, 채널 번호를 변경
	MP_USERCONN_CHANGE_CHANNEL_SYN,
	MP_USERCONN_CHANGE_CHANNEL_ACK,
	MP_USERCONN_CHANGE_CHANNEL_NACK,
	// 091106 LUJ, 리밋 던젼에서 지정된 채널로 플레이어를 이동시키기 위해 쓰임
	MP_USERCONN_FORCED_CHANNEL_SYN,
	MP_USERCONN_OPTION_SYN,
	MP_USERCONN_OPTION_ACK,
	MP_USERCONN_GETSERVERTIME_SYN,
	MP_USERCONN_GETSERVERTIME_ACK,
	// 100503 ShinJS --- 웹런처 로그인시 LoginID를 전달받음
	MP_USERCONN_GETLOGINID_ACK,

	// 100507 ShinJS --- 게임내 채널이동
	MP_USERCONN_CHANGE_CHANNEL_IN_GAME_SYN,
	MP_USERCONN_CHANGE_CHANNEL_IN_GAME_ACK,
	MP_USERCONN_CHANGE_CHANNEL_IN_GAME_NACK,
	MP_USERCONN_MONSTER_TAME_ACK,
	MP_USERCONN_BILLING_CHECK_SYN,
	MP_USERCONN_BILLING_CHECK_ACK,
	MP_USERCONN_BILLING_CHECK_NACK,
	MP_USERCONN_BILLING_START_ACK,
	MP_USERCONN_BILLING_START_NACK,
	MP_USERCONN_BILLING_STOP_SYN,
	MP_USERCONN_BILLING_STOP_ACK,
	MP_USERCONN_BILLING_ALERT_ACK,
	MP_USERCONN_BILLING_UPDATE_ACK,
};

enum MP_PROTOCOL_SKILLTREE
{
	MP_SKILLTREE_UPDATE_SYN,
	MP_SKILLTREE_UPDATE_ACK,
	MP_SKILLTREE_UPDATE_NACK,
	MP_SKILLTREE_POINT_NOTIFY,
};

enum MP_PROTOCOL_CHAT
{
	// MP_CHAT
	MP_CHAT_ALL,
	MP_CHAT_PARTY,
	MP_CHAT_GUILD,
	MP_CHAT_WHISPER,
	MP_CHAT_WHISPER_SYN,
	MP_CHAT_WHISPER_ACK,
	MP_CHAT_WHISPER_NACK,
	MP_CHAT_FROMMONSTER_ALL,
	MP_CHAT_MONSTERSPEECH,
	
	MP_CHAT_FASTCHAT,	//도배금지
	MP_CHAT_GM,
	MP_CHAT_WHISPER_GM,		//서버->클라이언트
	MP_CHAT_WHISPER_GM_SYN,	//서버에서-->서버로메세지

	MP_CHAT_SMALLSHOUT,		//자신의맵 자신의채널 전체만
	MP_CHAT_GM_SMALLSHOUT,
	
	MP_CHAT_SHOUT_SYN,
	MP_CHAT_SHOUT_ACK,
	MP_CHAT_SHOUT_NACK,
	MP_CHAT_SHOUT_SENDALL,
	MP_CHAT_SHOUT_SENDSERVER,
	
	MP_CHAT_GUILDUNION,

	// 061204 LYW --- Add New Chatting Protocol.
	MP_CHAT_WHOLE, 
	MP_CHAT_FAMILY, 
	MP_CHAT_ARMY, 
	MP_CHAT_TRADE, 
	MP_CHAT_NOTIFY, 
	MP_CHAT_NORMAL, 
	//MP_CHAT_ALLIANCE, 
	// 070402 LYW --- Add new chatting protocol.
	MP_CHAT_SYSTEM,

	// 061204 LYW --- Add Emoticon Protocol.
	MP_CHAT_SORRY, 
	MP_CHAT_DELIGHT, 
	MP_CHAT_SORROW, 
	MP_CHAT_HAHA, 
	MP_CHAT_SOLUTATION, 
	MP_CHAT_HELP, 
	MP_CHAT_HANDCLAP, 
	MP_CHAT_LOVE, 
	MP_CHAT_REMEDY, 
	MP_CHAT_THANKS, 
	MP_CHAT_THERE, 
	MP_CHAT_SCOLD, 

	// 070321 LYW --- Protocol : Add protocol to find user.
	MP_CHAT_FINDUSER,
	MP_CHAT_FIND_SUCCESS, 
	MP_CHAT_FIND_FAIL,

	// 100618 ONS 채팅 금지관련 추가
	MP_CHAT_FORBIDCHAT,
	MP_CHAT_PERMITCHAT,
};

enum MP_PROTOCOL_MOVE
{
	// MP_MOVE
	MP_MOVE_INIT,
	MP_MOVE_TARGET,
	MP_MOVE_CORRECTION,
	
	MP_MOVE_WALKMODE,
	MP_MOVE_RUNMODE,

	MP_MOVE_KYUNGGONG_SYN,
	MP_MOVE_KYUNGGONG_ACK,
	MP_MOVE_KYUNGGONG_NACK,
	
	MP_MOVE_STOP,
	
	MP_MOVE_EFFECTMOVE,

	MP_MOVE_MONSTERMOVE_NOTIFY,

	MP_MOVE_FORCESTOPKYUNGGONG,
	
	MP_MOVE_WARP,

	MP_MOVE_ONETARGET,

	MP_MOVE_PET_MOVE,
	MP_MOVE_PET_STOP,

	// 080930 LYW --- Protocol : 페이드 인/아웃 이동 추가.
	MP_FADEMOVE_SYN,
	MP_FADEMOVE_ACK,
	MP_FADEMOVE_NACK,
	// 081031 LUJ, 리콜 수락 여부
	MP_MOVE_RECALL_ASK_SYN,
	MP_MOVE_RECALL_ASK_SYN_TO_SERVER,
	MP_MOVE_RECALL_ASK_ACK,
	MP_MOVE_RECALL_ASK_ACK_TO_SERVER,
	MP_MOVE_RECALL_ASK_NACK,
	MP_MOVE_RECALL_ASK_NACK_TO_SERVER,
	// 081031 LUJ, 리콜 처리
	MP_MOVE_RECALL_SYN,
	MP_MOVE_RECALL_SYN_TO_SERVER,
	MP_MOVE_RECALL_ACK,
	MP_MOVE_RECALL_ACK_TO_SERVER,
	MP_MOVE_RECALL_NACK,
	MP_MOVE_RECALL_NACK_TO_SERVER,
	// 090316 LUJ, 탈것 이동
	MP_MOVE_VEHICLE_BEGIN_SYN,
	MP_MOVE_VEHICLE_BEGIN_ACK,
	MP_MOVE_VEHICLE_RECALL_SYN,
	MP_MOVE_VEHICLE_RECALL_ACK,
	MP_MOVE_KNOCKBACK_SYN,
	MP_MOVE_KNOCKBACK_ACK,
};

enum MP_PROTOCOL_ITEM
{
	// MP_ITEM
	MP_ITEM_TOTALINFO_LOCAL,
	MP_ITEM_STORAGEITEM_INFO,  //Ao￠?o¨uⓒ￢Ao

	MP_ITEM_USE_SYN,
	MP_ITEM_USE_ACK,
	MP_ITEM_USE_NACK,
	MP_ITEM_COMBINE_SYN,
	MP_ITEM_COMBINE_ACK,
	MP_ITEM_COMBINE_NACK,
	MP_ITEM_DIVIDE_SYN,
	MP_ITEM_DIVIDE_ACK,
	MP_ITEM_DIVIDE_NACK,
	MP_ITEM_DIVIDE_NEWITEM_NOTIFY,
	MP_ITEM_DISCARD_SYN,
	MP_ITEM_DISCARD_ACK,
	MP_ITEM_DISCARD_NACK,

	MP_ITEM_ERROR_NACK,

	MP_ITEM_MOVE_SYN,
	MP_ITEM_MOVE_ACK,
	MP_ITEM_MOVE_NACK,
	
	MP_ITEM_PET_MOVE_SYN,
	MP_ITEM_PET_MOVE_ACK,
	MP_ITEM_PET_MOVE_NACK,
	MP_ITEM_BUY_SYN,
	MP_ITEM_BUY_ACK,
	MP_ITEM_BUY_NACK,

	MP_ITEM_BUY_BY_COIN,				// 090227 ShinJS --- 암상인 추가작업 : Coin Item 구입시 Coin 제거 프로토콜
	MP_ITEM_SELL_SYN,
	MP_ITEM_SELL_ACK,
	MP_ITEM_SELL_NACK,		
	MP_ITEM_DEALER_SYN,
	MP_ITEM_DEALER_ACK,
	MP_ITEM_DEALER_NACK,
	
	MP_ITEM_MONEY,
	MP_ITEM_MONEY_ERROR,
	MP_ITEM_APPEARANCE_ADD,
	MP_ITEM_APPEARANCE_REMOVE,
	
	MP_ITEM_OBTAIN_MONEY,
	MP_ITEM_MONSTER_OBTAIN_NOTIFY,

	// 080130 LUJ, 옵션 전송
	MP_ITEM_OPTION_ADD_ACK,

	MP_ITEM_WORKING_START,	// 아이템 제작 작업(조합/인챈트/강화/분해) 중임을 알린다
	MP_ITEM_WORKING_STOP,	// 중지
	MP_ITEM_WORKING_FAIL,	// 실패
	MP_ITEM_WORKING_SUCCESS,// 성공
	MP_ITEM_WORKING_STARTEX,	// 아이템 제작 작업 중임을 알린다

	MP_ITEM_ENCHANT_SYN,
	MP_ITEM_ENCHANT_SUCCESS_ACK, 
	MP_ITEM_ENCHANT_FAILED_ACK, 
	MP_ITEM_ENCHANT_NACK,
	MP_ITEM_ENCHANT_LEVEL_NOTIFY,
	MP_ITEM_ENCHANT_LEVEL_NOTIFY_OTHER_AGENT,
	
	MP_ITEM_MIX_SYN,
	MP_ITEM_MIX_SUCCEED_ACK, 
	MP_ITEM_MIX_BIGFAILED_ACK,
	MP_ITEM_MIX_FAILED_ACK,
	MP_ITEM_MIX_GETITEM,
	MP_ITEM_MIX_NACK,
	
	MP_ITEM_REINFORCE_SYN,
	MP_ITEM_REINFORCE_SUCCEED_ACK,	
	MP_ITEM_REINFORCE_FAILED_ACK,
	MP_ITEM_REINFORCE_OPTION_ACK,	// 옵션 업데이트
	MP_ITEM_REINFORCE_NACK,
	
	MP_ITEM_DISSOLVE_SYN,
	MP_ITEM_DISSOLVE_ACK,
	MP_ITEM_DISSOLVE_NACK,
	MP_ITEM_DISSOLVE_GETITEM,

	MP_ITEM_MUNPA_COMBINE_SYN,
	MP_ITEM_MUNPA_COMBINE_ACK,
	MP_ITEM_MUNPA_COMBINE_NACK,
	
	MP_ITEM_MUNPA_MOVE_SYN,
	MP_ITEM_MUNPA_MOVE_ACK,
	MP_ITEM_MUNPA_MOVE_NACK,

	MP_ITEM_MUNPA_WAREHOUSE_INFO_SYN,
	MP_ITEM_MUNPA_WAREHOUSE_INFO_ACK,
	MP_ITEM_MUNPA_WAREHOUSE_INFO_NACK,
	
	MP_ITEM_ADDTO_MUNPAWARE_NOTIFY,
	MP_ITEM_DELETEFROM_MUNPAWARE_NOTIFY,

	MP_ITEM_MUNPA_WAREHOUSE_LEAVE,
	
	MP_ITEM_STORAGE_MOVE_SYN,
	MP_ITEM_STORAGE_MOVE_ACK,
	MP_ITEM_STORAGE_MOVE_NACK,

	MP_ITEM_STORAGE_COMBINE_SYN,
	MP_ITEM_STORAGE_COMBINE_ACK,
	MP_ITEM_STORAGE_COMBINE_NACK,

	MP_ITEM_STORAGE_ITEM_INFO_SYN,
	MP_ITEM_STORAGE_ITEM_INFO_ACK,
	MP_ITEM_STORAGE_ITEM_INFO_NACK,

	MP_ITEM_USE_FOR_QUESTSTART_SYN,
	MP_ITEM_USE_FOR_QUESTSTART_ACK,
	MP_ITEM_USE_FOR_QUESTSTART_NACK,

	MP_ITEM_USE_CHANGEITEM_SYN,		// event item _ change item
	MP_ITEM_USE_CHANGEITEM_ACK,
	MP_ITEM_USE_CHANGEITEM_NACK,

	MP_ITEM_GUILD_COMBINE_SYN,
	MP_ITEM_GUILD_COMBINE_ACK,
	MP_ITEM_GUILD_COMBINE_NACK,
	
	MP_ITEM_GUILD_MOVE_SYN,
	MP_ITEM_GUILD_MOVE_ACK,
	MP_ITEM_GUILD_MOVE_NACK,
	MP_ITEM_ADDTO_GUILDWARE_NOTIFY,
	MP_ITEM_DELETEFROM_GUILDWARE_NOTIFY,
	MP_ITEM_SHOPITEM_INFO_SYN,
	MP_ITEM_SHOPITEM_INFO_ACK,
	MP_ITEM_SHOPITEM_INFO_NACK,
	MP_ITEM_SHOPITEM_USE_ACK,
	MP_ITEM_SHOPITEM_USE_NACK,
	MP_ITEM_EVENTITEM_USE,
	
	MP_ITEM_SHOPITEM_PROTECTALL,
	MP_ITEM_SHOPITEM_CHARCHANGE_SYN,
	MP_ITEM_SHOPITEM_CHARCHANGE_ACK,
	MP_ITEM_SHOPITEM_CHARCHANGE_NACK,
	MP_ITEM_SHOPITEM_CHARCHANGE,
	MP_ITEM_USE_NOTIFY,	//일단 물약 사용 여부를 다른 캐릭터에 알리는데 사용
	MP_ITEM_SHOPITEM_SHOUT_SYN,
	MP_ITEM_SHOPITEM_SHOUT_ACK,
	MP_ITEM_SHOPITEM_SHOUT_NACK,
	MP_ITEM_SHOPITEM_SHOUT_SENDSERVER,
	MP_ITEM_SHOPITEM_SHOUT_SENDACK,

	MP_ITEM_CHANGEITEM_NACK,
	MP_ITEM_TIMELIMT_ITEM_ONEMINUTE,	// 071125 KTH --- 시간제 아이템의 시간이 1분미만일때...

	MP_ITEM_MAPMOVE_SCROLL_SYN,
	MP_ITEM_MAPMOVE_SCROLL_ACK,
	MP_ITEM_MAPMOVE_SCROLL_NACK,

	MP_ITEM_SKILL_SYN,
	MP_ITEM_SKILL_ACK,
	MP_ITEM_SKILL_NACK,

	// 071204 LYW --- Protocol : 스탯 초기화 프로토콜 추가.
	MP_ITEM_RESET_STATS_SYN,									// 스탯 초기화 요청.
	MP_ITEM_RESET_STATS_ACK,									// 스탯 초기화 성공.
	MP_ITEM_RESET_STATS_NACK,									// 스탯 초기화 실패.

	// 071204 LYW --- Protocl : 스킬 초기화 프로토콜 추가.
	MP_ITEM_RESET_SKILL_SYN,									// 스킬 초기화 요청.
	MP_ITEM_RESET_SKILL_ACK,									// 스킬 초기화 성공.
	MP_ITEM_RESET_SKILL_NACK,									// 스킬 초기화 실패.

	// 071210 KTH -- 인벤 토리 확장
	MP_ITEM_INCREASE_INVENTORY_SYN,
	MP_ITEM_INCREASE_INVENTORY_ACK,
	MP_ITEM_INCREASE_INVENTORY_NACK,

	MP_ITEM_CHANGE_CHARACTER_NAME_SYN,
	MP_ITEM_CHANGE_CHARACTER_NAME_ACK,
	MP_ITEM_CHANGE_CHARACTER_NAME_NACK,
	// 080215 LUJ, 유료 옵션 적용
	MP_ITEM_APPLY_OPTION_SYN,
	MP_ITEM_APPLY_OPTION_ACK,
	MP_ITEM_APPLY_OPTION_NACK,

	MP_ITEM_ENCHANT_EFFECT_NOTIFY,

	MP_ITEM_GIFT_EVENT_START,
	MP_ITEM_GIFT_EVENT_NOTIFY,

	MP_ITEM_PET_HATCH_ACK,
	// 080916 LUJ, 아이템 합성
	MP_ITEM_COMPOSE_SYN,
	MP_ITEM_COMPOSE_ACK,
	MP_ITEM_COMPOSE_NACK,

	MP_ITEM_CHANGESIZE_ACK,
	MP_ITEM_CHANGESIZE_NACK,

	MP_ITEM_USEEFFECT_ACK,
	MP_ITEM_USEEFFECT_NACK,

	MP_ITEM_COOK_GETITEM,
	MP_ITEM_COOK_ACK,

	MP_ITEM_HOUSE_RESTORED,
	MP_ITEM_HOUSE_BONUS,

	// 100517 ONS 전직 초기화 아이템관련 프로토콜 추가.
	MP_ITEM_CHANGE_CLASS_SYN,
	MP_ITEM_CHANGE_CLASS_ACK,
	MP_ITEM_CHANGE_CLASS_NACK,
};

enum MP_PROTOCOL_CHEAT
{
	MP_CHEAT_MOVE_SYN,
	MP_CHEAT_MOVE_ACK,
	MP_CHEAT_MOVE_NACK,

	MP_CHEAT_CHANGEMAP_SYN,
	MP_CHEAT_CHANGEMAP_ACK,
	MP_CHEAT_CHANGEMAP_NACK,
	MP_CHEAT_ITEM_SYN,
	MP_CHEAT_ITEM_ACK,
	MP_CHEAT_ITEM_NACK,
	
	MP_CHEAT_MANA_SYN, 
	MP_CHEAT_MANA_ACK, 
	MP_CHEAT_MANA_NACK, 
	MP_CHEAT_MONEY_SYN,
	MP_CHEAT_MONEY_ACK,
	MP_CHEAT_MONEY_NACK,

	MP_CHEAT_RELOADING,

	MP_CHEAT_PET_LEVELUP_SYN,

	MP_CHEAT_LEVELUP_SYN,
	MP_CHEAT_LEVELUP_ACK,
	MP_CHEAT_LEVELUP_NACK,
	MP_CHEAT_MOVETOCHAR_SYN,
	MP_CHEAT_MOVETOCHAR_ACK,
	MP_CHEAT_MOVETOCHAR_NACK,

	MP_CHEAT_WHEREIS_SYN,
	MP_CHEAT_WHEREIS_ACK,
	MP_CHEAT_WHEREIS_NACK,

	MP_CHEAT_BANCHARACTER_SYN,	//client(gm) -> map; map -> agent
	MP_CHEAT_BANCHARACTER_ACK,	//agent -> client(gm)
	MP_CHEAT_BANCHARACTER_NACK,	//agent or map ->client(gm)

	MP_CHEAT_BLOCKCHARACTER_SYN,	//client(gm) -> map; map -> agent
	MP_CHEAT_BLOCKCHARACTER_ACK,	//agent -> client(gm)
	MP_CHEAT_BLOCKCHARACTER_NACK,	//agent or map ->client(gm)

	MP_CHEAT_GETID_SYN,
	MP_CHEAT_GETID_ACK,
	MP_CHEAT_GETID_NACK,	
	
	MP_CHEAT_PKALLOW_SYN,
	MP_CHEAT_PKALLOW_ACK,
	MP_CHEAT_PKALLOW_NACK,

	MP_CHEAT_MOVEUSER_SYN,
	MP_CHEAT_MOVEUSER_ACK,
	MP_CHEAT_MOVEUSER_NACK,

	MP_CHEAT_HIDE_SYN,
	MP_CHEAT_HIDE_ACK,
	MP_CHEAT_HIDE_NACK,
	MP_CHEAT_WHEREIS_MAPSERVER_ACK,
	
	MP_CHEAT_EVENT_MONSTER_REGEN,
	MP_CHEAT_EVENT_MONSTER_DELETE,
	MP_CHEAT_UPDATE_SKILL_SYN,
	MP_CHEAT_UPDATE_SKILL_ACK,
	MP_CHEAT_UPDATE_SKILL_NACK,
	
	MP_CHEAT_BANMAP_SYN,
	MP_CHEAT_BANMAP_ACK,
	MP_CHEAT_BANMAP_NACK,
	
	MP_CHEAT_STR_SYN,
	MP_CHEAT_STR_ACK,
	MP_CHEAT_STR_NACK,

	MP_CHEAT_DEX_SYN,
	MP_CHEAT_DEX_ACK,
	MP_CHEAT_DEX_NACK,

	MP_CHEAT_VIT_SYN,
	MP_CHEAT_VIT_ACK,
	MP_CHEAT_VIT_NACK,
	
	MP_CHEAT_WIS_SYN,
	MP_CHEAT_WIS_ACK,
	MP_CHEAT_WIS_NACK,
	
	MP_CHEAT_INT_SYN,
	MP_CHEAT_INT_ACK,
	MP_CHEAT_INT_NACK,

	MP_CHEAT_AGENTCHECK_SYN,
	MP_CHEAT_AGENTCHECK_ACK,
	MP_CHEAT_AGENTCHECK_NACK,
	
	MP_CHEAT_GM_LOGIN_SYN,
	MP_CHEAT_GM_LOGIN_ACK,
	MP_CHEAT_GM_LOGIN_NACK,

	MP_CHEAT_KILL_ALLMONSTER_SYN,
	MP_CHEAT_KILL_ALLMONSTER_ACK,
	MP_CHEAT_KILL_ALLMONSTER_NACK,
	
	MP_CHEAT_PARTYINFO_SYN,
	MP_CHEAT_PARTYINFO_ACK,
	MP_CHEAT_PARTYINFO_NACK,
	
	MP_CHEAT_NOTICE_SYN,

	MP_CHEAT_EVENT_SYN,	
	
	MP_CHEAT_MUNPADATECLR_SYN,
	MP_CHEAT_EVENTNOTIFY_ON,
	MP_CHEAT_EVENTNOTIFY_OFF,
	MP_CHEAT_PLUSTIME_ALLOFF,
	MP_CHEAT_PLUSTIME_ON,
	MP_CHEAT_PLUSTIME_OFF,
	MP_CHEAT_GUILDUNION_CLEAR,
	MP_CHEAT_MOB_CHAT,
	MP_CHEAT_NPCHIDE_SYN,
	MP_CHEAT_NPCHIDE_ACK,
	MP_CHEAT_NPCHIDE_NACK,
	MP_CHEAT_SKILLPOINT_SYN,
	MP_CHEAT_SKILLPOINT_ACK,
	MP_CHEAT_SKILLPOINT_NACK,

	MP_CHEAT_GOD_SYN,
	// 081022 LYW --- Pet : 펫 버그/기타 테스트를 위하여 Pet에도 GOD 모드를 적용한다.
	MP_CHEAT_PETGOD_SYN,
	// 071212 KTH -- Protocol : Reset Character Inventory
	MP_CHEAT_RESET_INVENTORY_SYN,
	MP_CHEAT_RESET_INVENTORY_ACK,

	MP_CHEAT_PVP_DAMAGE_RATE_SYN,
	MP_CHEAT_PVP_DAMAGE_RATE_ACK,
	MP_CHEAT_CELAR_INVENTORY_SYN,
	MP_CHEAT_CELAR_INVENTORY_ACK,

//---KES PKEVENT
	MP_CHEAT_PKEVENT,
	MP_CHEAT_MONSTER_SCRIPT_SYN,
	MP_CHEAT_MONSTER_SCRIPT_ACK,
	MP_CHEAT_MONSTER_SCRIPT_NACK,
	MP_CHEAT_CHANGESIZE,
	MP_CHEAT_VEHICLE_SUMMON_SYN,
	MP_CHEAT_VEHICLE_SUMMON_NACK,
	MP_CHEAT_VEHICLE_SUMMON_ACK,
	MP_CHEAT_VEHICLE_GET_SYN,
	MP_CHEAT_VEHICLE_GET_ACK,
	MP_CHEAT_VEHICLE_UNSUMMON_SYN,
	MP_CHEAT_VEHICLE_UNSUMMON_ACK,
	MP_CHEAT_FISHING_FISHINGEXP,
	MP_CHEAT_FISHING_FISHPOINT,

	// 인던 모니터링
	MP_CHEAT_DUNGEON_OBSERVER_SYN,
	MP_CHEAT_DUNGEON_OBSERVER_ACK,
	MP_CHEAT_DUNGEON_OBSERVER_NACK,

	MP_CHEAT_DUNGEON_OBSERVERJOIN_SYN,
	MP_CHEAT_DUNGEON_OBSERVERJOIN_NACK,

	MP_CHEAT_DUNGEON_GETINFOALL_SYN,
	MP_CHEAT_DUNGEON_GETINFOALL_ACK,

	MP_CHEAT_DUNGEON_GETINFOONE_SYN,
	MP_CHEAT_DUNGEON_GETINFOONE_ACK,

	// 채팅 금지
	MP_CHEAT_FORBID_CHAT_SYN,
	MP_CHEAT_FORBID_CHAT_ACK,
	MP_CHEAT_FORBID_CHAT_OTHERMAP_SYN,
	MP_CHEAT_FORBID_ALREADYEXIST,
	MP_CHEAT_FORBID_NONTARGET,
	MP_CHEAT_PERMIT_CHAT_SYN,
	MP_CHEAT_PERMIT_CHAT_ACK,
	MP_CHEAT_PERMIT_CHAT_OTHERMAP_SYN,
};

enum MP_PROTOCOL_QUICK
{
	MP_QUICK_INFO,

	MP_QUICK_ADD_SYN,
	MP_QUICK_ADD_ACK,
	MP_QUICK_ADD_NACK,

	MP_QUICK_REMOVE_SYN,
	MP_QUICK_REMOVE_ACK,
	MP_QUICK_REMOVE_NACK,

	MP_QUICK_CHANGE_SYN,
	MP_QUICK_CHANGE_ACK,
	MP_QUICK_CHANGE_NACK,
};

enum MP_PROTOCOL_PACKEDDATA
{
	MP_PACKEDDATA_NORMAL,
	
	MP_PACKEDDATA_TOMAPSERVER,
	MP_PACKEDDATA_TOBROADMAPSERVER,
};

enum MP_PROTOCOL_PARTY
{
	// ¨¡A¨¡¨u ￠￢￠c¨o¨￢¨¡￠c￠￢| ¨￢￠￢￠?¨IA¨ª￠￥U. 
	MP_PARTY_INFO,

	// ¨¡A¨¡¨u ￠￢￠￢￥ie¡¾a E￠cAI 
	MP_PARTY_CREATE_SYN,
	MP_PARTY_CREATE_ACK, 
	MP_PARTY_CREATE_NACK,
	// ¨¡A¨¡¨u Aⓒ￢¡Æ￠®
	MP_PARTY_ADD_SYN,
	MP_PARTY_ADD_ACK,
	MP_PARTY_ADD_NACK,

	MP_PARTY_ADD_INVITE, //￠￢¨­¨oAAoⓒoU¨o¨￢

	MP_PARTY_INVITE_ACCEPT_SYN,
	MP_PARTY_INVITE_ACCEPT_ACK, //ⓒoⓒ¡Aa￠?￠®¡ÆO ¨￢￠￢ⓒø¡i AE￠￥eAⓒ￢AI￠Oo¡Æi ￠￢¨­¨oAAo CN￠￥U
	MP_PARTY_INVITE_ACCEPT_NACK,

	MP_PARTY_INVITE_DENY_SYN, //¨¡A¨¡¨u AE￠￥e ¡ÆAAy
	MP_PARTY_INVITE_DENY_ACK,
	MP_PARTY_INVITE_DENY_NACK,
	

	MP_PARTY_NOTIFYADD_TO_MAPSERVER,
	// ¨¡A¨¡¨u ¡ief	
	MP_PARTY_DEL_SYN,
	MP_PARTY_DEL_ACK,
	MP_PARTY_DEL_NACK, 
	MP_PARTY_NOTIFYDELETE_TO_MAPSERVER,
	MP_PARTY_SYNDELETE_TO_MAPSERVER,
	// Aⓒ￢ⓒoⓒ¡ 
	MP_PARTY_BAN_SYN,
	MP_PARTY_BAN_ACK,
	MP_PARTY_BAN_NACK,
	MP_PARTY_NOTIFYBAN_TO_MAPSERVER,
	// ￠￢￠c￠￥o¡¾C AI¨uc
	MP_PARTY_CHANGEMASTER_SYN, 
	MP_PARTY_CHANGEMASTER_ACK,
	MP_PARTY_CHANGEMASTER_NACK,
	MP_PARTY_NOTIFYCHANGEMASTER_TO_MAPSERVER,
	//¨¡A¨¡¨u C¨ª¡ie
	MP_PARTY_BREAKUP_SYN,
	MP_PARTY_BREAKUP_ACK,
	MP_PARTY_BREAKUP_NACK,
	MP_PARTY_NOTIFYBREAKUP_TO_MAPSERVER,

	MP_PARTY_MEMBER_LOGIN,
	MP_PARTY_NOTIFYMEMBER_LOGIN_TO_MAPSERVER,
	MP_PARTY_MEMBER_LOGOUT,
	MP_PARTY_NOTIFYMEMBER_LOGOUT_TO_MAPSERVER,
		
	MP_PARTY_MEMBERLIFE,
	MP_PARTY_MEMBERMANA,	
	MP_PARTY_MEMBERLEVEL,
	MP_PARTY_SENDPOS,
	MP_PARTY_REVIVEPOS,

	// 070110 LYW --- Add protocol for change pickup item.
	MP_PARTY_CHANGE_PICKUPITEM_SYN,
	MP_PARTY_CHANGE_PICKUPITEM_ACK,
	MP_PARTY_CHANGE_PICKUPITEM_NACK,
	MP_PARTY_CHANGE_DICEGRADE_SYN,
	MP_PARTY_CHANGE_DICEGRADE_ACK,
	MP_PARTY_CHANGE_DICEGRADE_NACK,
	MP_PARTY_NOTIFYCHANGES_TO_MAPSERVER,
	MP_PARTY_CLEAR,
	MP_PARTY_NOTIFYCREATE_TO_MAPSERVER,
	
	MP_PARTY_MEMBER_LOGINMSG,
	MP_PARTY_NOTIFYMEMBER_LOGINMSG,
	
	MP_PARTY_NOTIFYMEMBER_LEVEL,

	MP_PARTY_MONSTER_OBTAIN_NOTIFY,
	MP_PARTY_MONSTER_OBTAIN_BYDICE_NOTIFY,
	MP_PARTY_OBTAIN_MONEY_TO_PARTY,

	// 071002 LYW --- Protocol : Add protocol for change option of party.
	MP_PARTY_NOTIFY_CHANGE_OPTION,
	
	// 071003 LYW --- Protocol : Add protocol for send message that initialized player.
	//MP_PARTY_REAL_MEMBER_LOGIN,

	// 090525 ShinJS --- 이름으로 파티초대
	MP_PARTY_INVITE_BYNAME_SYN,
	MP_PARTY_INVITE_BYNAME_ACK,
	MP_PARTY_INVITE_BYNAME_NACK,

	// 090525 ShinJS --- 이름으로 파티초대한 경우 Accept 처리
	MP_PARTY_INVITE_BYNAME_ACCEPT_SYN,
	MP_PARTY_INVITE_BYNAME_ACCEPT_ACK,
	MP_PARTY_INVITE_BYNAME_ACCEPT_NACK,

	MP_PARTY_INSTANTPARTY_REGIST_SYN,
};

enum MP_PROTOCOL_SIGNAL
{
	//MP_SIGNAL
	MP_SIGNAL_COMMONUSER,
	MP_SIGNAL_ONEUSER,
	MP_SIGNAL_SYSTEM,

	MP_SIGNAL_BATTLE,
	MP_SIGNAL_SHOWDOWN_RESULT,

	MP_SIGNAL_USER_ADD_ITEM,
};

enum MP_PROTOCOL_SKILL
{
	MP_SKILL_START_SYN,
	MP_SKILL_START_DESTROY_ACK,
	MP_SKILL_START_NACK,

	MP_SKILL_SKILLOBJECT_ADD,
	MP_SKILL_SKILLOBJECT_REMOVE,
	MP_SKILL_SKILL_RESULT,
	MP_SKILL_UPDATE_TARGET_SYN,
	// 091127 LUJ, 플레이어를 소환한다
	MP_SKILL_RECALL_SYN,
	MP_SKILL_CANCEL_SYN,
	MP_SKILL_CANCEL_NACK,
	MP_SKILL_CANCEL_NOTIFY,

	MP_SKILL_DELAY_RESET_NOTIFY,

	MP_SKILL_COUNT_NOTIFY,

	// 080602 LUJ, 세계 대상 스킬을 다른 서버로 전파한다
	MP_SKILL_START_TO_MAP,
	// 080602 LUJ, 스킬 발동 시 소모 조건을 충족하지 못함
	MP_SKILL_CONSUME_NACK,

	// 100211 ONS 부활계열 스킬 사용시 대상자에게 부활의사를 묻는 처리 추가.
	MP_SKILL_RESURRECT_SYN,
	MP_SKILL_RESURRECT_ACK,
	MP_SKILL_RESURRECT_NACK,

	// 100614 ShinJS --- 버프 해제조건으로 인하여 생성 실패시 알림.
	MP_SKILL_BUFF_START_FAIL_NOTIFY,
};

enum MP_PROTOCOL_STORAGE
{
//Ao￠?i¡ÆI
	MP_STORAGE_LISTINFO_SYN,
	MP_STORAGE_LISTINFO_ACK,
	MP_STORAGE_LISTINFO_NACK,
//	
	MP_STORAGE_BUY_SYN,
	MP_STORAGE_BUY_ACK,
	MP_STORAGE_BUY_NACK,
	
	MP_STORAGE_DEL_SYN,
	MP_STORAGE_DEL_ACK,
	MP_STORAGE_DEL_NACK,
	
	MP_STORAGE_PUTIN_MONEY_SYN,
	MP_STORAGE_PUTIN_MONEY_ACK,
	MP_STORAGE_PUTIN_MONEY_NACK,

	MP_STORAGE_PUTOUT_MONEY_SYN,
	MP_STORAGE_PUTOUT_MONEY_ACK,
	MP_STORAGE_PUTOUT_MONEY_NACK,

	//MP_STORAGE_INFO,
};

enum MP_PROTOCOL_EXCHANGE
{
	MP_EXCHANGE_APPLY,			//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c
	MP_EXCHANGE_APPLY_SYN,		//¡¾ⓒøE?¨oAA¡i
	MP_EXCHANGE_APPLY_ACK,
	MP_EXCHANGE_APPLY_NACK,

	MP_EXCHANGE_ACCEPT,			//¡¾ⓒøE?¨oA￠Oo
	MP_EXCHANGE_ACCEPT_SYN,
	MP_EXCHANGE_ACCEPT_ACK,
	MP_EXCHANGE_ACCEPT_NACK,

	MP_EXCHANGE_CANTAPPLY,

	MP_EXCHANGE_REJECT,				//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c
	MP_EXCHANGE_REJECT_SYN,			//¡¾ⓒøE?¡ÆAAy
//	MP_EXCHANGE_REJECT_ACK,
//	MP_EXCHANGE_REJECT_NACK,

	MP_EXCHANGE_WAITING_CANCEL,
	MP_EXCHANGE_WAITING_CANCEL_SYN,
	MP_EXCHANGE_WAITING_CANCEL_ACK,
	MP_EXCHANGE_WAITING_CANCEL_NACK,

	MP_EXCHANGE_START,			//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c // ¡¾ⓒøE? ¨oAAU

	MP_EXCHANGE_ADDITEM,		//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c //¡io￠￥eAC ¨u¨¡AIAU Aⓒ￢¡Æ￠® ¨uE￠￢ⓒ÷
	MP_EXCHANGE_ADDITEM_SYN,	//¨u¨¡AIA¨¡ Aⓒ￢¡Æ￠®
	MP_EXCHANGE_ADDITEM_ACK,
	MP_EXCHANGE_ADDITEM_NACK,

	MP_EXCHANGE_DELITEM,		//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c //¡io￠￥eAC ¨u¨¡AIAU ¡ief ¨uE￠￢ⓒ÷
	MP_EXCHANGE_DELITEM_SYN,	//¨u¨¡AIAU ¡ief
	MP_EXCHANGE_DELITEM_ACK,
	MP_EXCHANGE_DELITEM_NACK,

	MP_EXCHANGE_INPUTMONEY,		//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c //¡io￠￥eAC ￥i¡¤ AO¡¤A
	MP_EXCHANGE_INPUTMONEY_SYN,
	MP_EXCHANGE_INPUTMONEY_ACK,
	MP_EXCHANGE_INPUTMONEY_NACK,
	
	MP_EXCHANGE_LOCK,			//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c
	MP_EXCHANGE_LOCK_SYN,		//LOCK
	MP_EXCHANGE_LOCK_ACK,
	MP_EXCHANGE_LOCK_NACK,

	MP_EXCHANGE_UNLOCK,			//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c
	MP_EXCHANGE_UNLOCK_SYN,		//UNLOCK
	MP_EXCHANGE_UNLOCK_ACK,
	MP_EXCHANGE_UNLOCK_NACK,

	MP_EXCHANGE_EXCHANGE,		//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c
	MP_EXCHANGE_EXCHANGE_SYN,	//¡¾ⓒøE?ⓒoo¨¡¡Æ
	MP_EXCHANGE_EXCHANGE_ACK,
	MP_EXCHANGE_EXCHANGE_NACK,

	MP_EXCHANGE_CANCEL,			//¨u¡ⓒⓒoo-->A¡þ￠OoAI¨uⓒ￡¨¡￠c
	MP_EXCHANGE_CANCEL_SYN,		//Ae¨uO
	MP_EXCHANGE_CANCEL_ACK,
	MP_EXCHANGE_CANCEL_NACK,

	MP_EXCHANGE_INSERT,
	MP_EXCHANGE_REMOVE,
	MP_EXCHANGE_SETMONEY,
};

enum MP_PROTOCOL_STREESTALL
{
	MP_STREETSTALL_START, // ￥i￠?AU
	MP_STREETSTALL_END,

	MP_STREETSTALL_OPEN_SYN, // ¡iy¨u¨￢..
	MP_STREETSTALL_OPEN_ACK,
	MP_STREETSTALL_OPEN_NACK,

	MP_STREETSTALL_CLOSE_SYN, // ~¡¤a..
	MP_STREETSTALL_CLOSE_ACK,
	MP_STREETSTALL_CLOSE_NACK,
	MP_STREETSTALL_CLOSE,

	MP_STREETSTALL_LOCKITEM_SYN,		//LOCK (¡ioC¡Æ￥ii¡¤I)..
	MP_STREETSTALL_LOCKITEM_ACK,
	MP_STREETSTALL_LOCKITEM_NACK,
	MP_STREETSTALL_LOCKITEM,
	
	MP_STREETSTALL_UNLOCKITEM_SYN,		//UNLOCK (¡ioC¡Æ¨uod)..
	MP_STREETSTALL_UNLOCKITEM_ACK,
	MP_STREETSTALL_UNLOCKITEM_NACK,
	MP_STREETSTALL_UNLOCKITEM,

	MP_STREETSTALL_DELETEITEM_SYN,		// ¡ioC¡ÆAC ¡ief..
	MP_STREETSTALL_DELETEITEM_ACK,
	MP_STREETSTALL_DELETEITEM_NACK,
	MP_STREETSTALL_DELETEITEM,

	MP_STREETSTALL_BUYITEM,
	MP_STREETSTALL_BUYITEM_ERROR,
	MP_STREETSTALL_BUYITEM_SYN,		// ¡ioC¡Æ ¡ic¡¾a..
	MP_STREETSTALL_BUYITEM_ACK,
	MP_STREETSTALL_BUYITEM_NACK,
	MP_STREETSTALL_SELLITEM,
	MP_STREETSTALL_SELLITEM_ERROR,
	MP_STREETSTALL_SELLITEM_SYN,		
	MP_STREETSTALL_SELLITEM_ACK,
	MP_STREETSTALL_SELLITEM_NACK,


	MP_STREETSTALL_GUESTIN_SYN,
	MP_STREETSTALL_GUESTIN_ACK,
	MP_STREETSTALL_GUESTIN_NACK,

	MP_STREETSTALL_GUESTOUT_SYN,
	MP_STREETSTALL_GUESTOUT_ACK,
	MP_STREETSTALL_GUESTOUT_NACK,
	
	MP_STREETSTALL_EDITTITLE_SYN, // f￠￢n ¨uod..
	MP_STREETSTALL_EDITTITLE_ACK,
	MP_STREETSTALL_EDITTITLE_NACK,
	MP_STREETSTALL_EDITTITLE,
	
	MP_STREETSTALL_UPDATEITEM,
	MP_STREETSTALL_UPDATE_SYN,
	MP_STREETSTALL_UPDATE_ACK,
	MP_STREETSTALL_UPDATE_NACK,
	MP_STREETSTALL_UPDATE,
	MP_STREETSTALL_UPDATEEND_SYN,
	MP_STREETSTALL_UPDATEEND_ACK,
	MP_STREETSTALL_UPDATEEND_NACK,
	MP_STREETSTALL_UPDATEEND,
	
	MP_STREETSTALL_FAKEREGISTITEM_SYN,			// CNⓒoⓒª￠?￠® ~CO ￥ii¡¤I
	MP_STREETSTALL_FAKEREGISTITEM_ACK,
	MP_STREETSTALL_FAKEREGISTITEM_NACK,
	MP_STREETSTALL_FAKEREGISTITEM,

	MP_STREETSTALL_FAKEREGISTBUYITEM_SYN,			// CNⓒoⓒª￠?￠® ~CO ￥ii¡¤I
	MP_STREETSTALL_FAKEREGISTBUYITEM_ACK,
	MP_STREETSTALL_FAKEREGISTBUYITEM_NACK,
	MP_STREETSTALL_FAKEREGISTBUYITEM,

	MP_STREETSTALL_MESSAGE,
};


enum MP_PROTOCOL_BATTLE
{
	MP_BATTLE_INFO,

	MP_BATTLE_CHAT_TEAM_SYN,
	MP_BATTLE_CHAT_TEAM_ACK,
	MP_BATTLE_CHAT_TEAM_NACK,

	MP_BATTLE_CHAT_MASTER_SYN,
	MP_BATTLE_CHAT_MASTER_ACK,
	MP_BATTLE_CHAT_MASTER_NACK,
	
	MP_BATTLE_START_NOTIFY,
	MP_BATTLE_TEAMMEMBER_ADD_NOTIFY,
	MP_BATTLE_TEAMMEMBER_DELETE_NOTIFY,
	MP_BATTLE_TEAMMEMBER_DIE_NOTIFY,
	MP_BATTLE_BATTLEOBJECT_DESTROY_NOTIFY,
	MP_BATTLE_BATTLEOBJECT_CREATE_NOTIFY,
	MP_BATTLE_VICTORY_NOTIFY,
	MP_BATTLE_DRAW_NOTIFY,
	MP_BATTLE_DESTROY_NOTIFY,

	MP_BATTLE_RESULT,

	MP_BATTLE_CHANGE_OBJECTBATTLE,
	
//KES SHOWDOWN TEST 031020
	MP_BATTLE_SHOWDOWN_REQUEST_SYN,
	MP_BATTLE_SHOWDOWN_REQUEST_ACK,
	MP_BATTLE_SHOWDOWN_REQUEST_NACK,
	MP_BATTLE_SHOWDOWN_APPLY,
	MP_BATTLE_SHOWDOWN_APPLY_SYN,
	MP_BATTLE_SHOWDOWN_APPLY_ACK,
	MP_BATTLE_SHOWDOWN_APPLY_NACK,

	MP_BATTLE_SHOWDOWN_WAITING_CANCEL,
	MP_BATTLE_SHOWDOWN_WAITING_CANCEL_SYN,
	MP_BATTLE_SHOWDOWN_WAITING_CANCEL_ACK,
	MP_BATTLE_SHOWDOWN_WAITING_CANCEL_NACK,

	MP_BATTLE_SHOWDOWN_ACCEPT,
	MP_BATTLE_SHOWDOWN_ACCEPT_SYN,
	MP_BATTLE_SHOWDOWN_ACCEPT_ACK,
	MP_BATTLE_SHOWDOWN_ACCEPT_NACK,

	MP_BATTLE_SHOWDOWN_REJECT,
	MP_BATTLE_SHOWDOWN_REJECT_SYN,
	MP_BATTLE_SHOWDOWN_REJECT_ACK,
	MP_BATTLE_SHOWDOWN_REJECT_NACK,
	
	MP_BATTLE_SHOWDOWN_CREATESTAGE,
	
	MP_BATTLE_SHOWDOWN_ERROR,

	MP_BATTLE_SIEGEWAR_BATTLEINFO,
};


enum MP_PROTOCOL_CHAR_REVIVE
{
	MP_CHAR_REVIVE_PRESENTSPOT_SYN,
	MP_CHAR_REVIVE_PRESENTSPOT_ACK,
	MP_CHAR_REVIVE_PRESENTSPOT_NACK,

	MP_CHAR_REVIVE_LOGINSPOT_SYN,	
	MP_CHAR_REVIVE_LOGINSPOT_ACK,
	MP_CHAR_REVIVE_LOGINSPOT_NACK,

	MP_CHAR_REVIVE_VILLAGESPOT_SYN,
	MP_CHAR_REVIVE_VILLAGESPOT_ACK,
	MP_CHAR_REVIVE_VILLAGESPOT_NACK,
};

enum MP_PROTOCOL_FRIEND
{
	MP_FRIEND_ADD_SYN,
	MP_FRIEND_ADD_ACK,
	MP_FRIEND_ADD_NACK,
	
	MP_FRIEND_ADD_INVITE,
	MP_FRIEND_ADD_ACCEPT,
	MP_FRIEND_ADD_ACCEPT_ACK,
	MP_FRIEND_ADD_ACCEPT_NACK,
	MP_FRIEND_ADD_DENY,

	MP_FRIEND_DEL_SYN,
	MP_FRIEND_DEL_ACK,
	MP_FRIEND_DEL_NACK,

	MP_FRIEND_DELID_SYN,
	MP_FRIEND_DELID_ACK,

	MP_FRIEND_SHOW_LIST_SYN, //¨uE¨u￠￥￠￥U. Ao￠?o¨uⓒ￢Ao. start
	MP_FRIEND_SHOW_LIST_ACK,
	MP_FRIEND_SHOW_LIST_NACK, // end
		 	
	MP_FRIEND_LOGIN, //C->A
	MP_FRIEND_LOGIN_NOTIFY, //ⓒø¨￡￠￢| ￥ii¡¤ICN A¡I¡¾￠￢￥ie￠?￠®¡ÆO. A->C
	MP_FRIEND_LOGIN_FRIEND, // ⓒø¡i¡Æ￠® ￥ii¡¤ICN A¡I¡¾￠￢￥ie A->C
	
	MP_FRIEND_LOGOUT_NOTIFY, //from MAP to CLIENT
	MP_FRIEND_LOGOUT_NOTIFY_TO_AGENT, //from MAP to AGENT
	MP_FRIEND_LOGOUT_NOTIFY_TO_CLIENT, 
	MP_FRIEND_LOGOUT_NOTIFY_AGENT_TO_AGENT, //from AGENT to AGENT
	
	MP_FRIEND_ADDID_SYN,
	MP_FRIEND_ADDID_ACK,
	MP_FRIEND_ADDID_NACK,

	
	MP_FRIEND_LIST_SYN,
	MP_FRIEND_LIST_ACK,
	MP_FRIEND_LIST_NACK,

	//from AGENT to AGENT
	MP_FRIEND_ADD_ACCEPT_TO_AGENT,
	MP_FRIEND_LOGIN_NOTIFY_TO_AGENT,
	MP_FRIEND_ADD_INVITE_TO_AGENT,
	MP_FRIEND_ADD_ACK_TO_AGENT,
	MP_FRIEND_ADD_NACK_TO_AGENT,
	MP_FRIEND_ADD_ACCEPT_NACK_TO_AGENT,
};

enum MP_PROTOCOL_NOTE
{
	MP_NOTE_SENDNOTE_SYN,
	MP_NOTE_SENDNOTE_ACK,
	MP_NOTE_SENDNOTE_NACK,
	
	MP_NOTE_SENDNOTEID_SYN,

	MP_NOTE_RECEIVENOTE,
	
	MP_NOTE_DELNOTE_SYN,
	MP_NOTE_DELNOTE_ACK,
	MP_NOTE_DELNOTE_NACK,
	
	MP_NOTE_DELALLNOTE_SYN,
	MP_NOTE_DELALLNOTE_ACK,
	MP_NOTE_DELALLNOTE_NACK,
	
	MP_NOTE_NOTELIST_SYN, 
	MP_NOTE_NOTELIST_ACK,
	MP_NOTE_NOTELIST_NACK,
	

	MP_NOTE_READNOTE_SYN,
	MP_NOTE_READNOTE_ACK,
	MP_NOTE_READNOTE_WITH_PACKAGE_ACK,
	MP_NOTE_READNOTE_NACK,
	
	MP_NOTE_NEW_NOTE,

	MP_NOTE_SAVENOTE_SYN,
	MP_NOTE_SAVENOTE_ACK,
	MP_NOTE_SAVENOTE_NACK,

	MP_NOTE_GETPACKAGE_SYN,
	MP_NOTE_GETPACKAGE_ACK,
	MP_NOTE_GETPACKAGE_NACK,
	MP_NOTE_GETPACKAGE_NOTIFY,
};

enum MP_PROTOCOL_BOSSMONSTER
{
	MP_BOSS_REST_START_NOTIFY,
	MP_BOSS_RECALL_NOTIFY,
	MP_BOSS_LIFE_NOTIFY,
	MP_BOSS_STAND_END_NOTIFY,
	MP_FIELD_LIFE_NOTIFY,
};

enum MP_PROTOCOL_NPC
{
	MP_NPC_SPEECH_SYN,
	MP_NPC_SPEECH_ACK,
	MP_NPC_SPEECH_NACK,

	MP_NPC_CLOSEBOMUL_SYN,
	MP_NPC_CLOSEBOMUL_ACK,
	MP_NPC_CLOSEBOMUL_NACK,	
	
	MP_NPC_OPENBOMUL_SYN,
	MP_NPC_OPENBOMUL_ACK,
	MP_NPC_OPENBOMUL_NACK,
	
	MP_NPC_DOJOB_SYN,
	MP_NPC_DOJOB_ACK,
	MP_NPC_DOJOB_NACK,

	// KTH --- NPC 스크립트 실행 함수중 서버의 확인절차 추가
	MP_NPC_CHECK_HACK_SYN,
	MP_NPC_CHECK_HACK_ACK,
	MP_NPC_CHECK_HACK_NACK,
	
	MP_NPC_DIE_ACK,

	// 090227 ShinJS --- 이동 NPC 추가/제거 프로토콜
	MP_NPC_READYTOMOVE_NOTIFY,		// 이동NPC 이동전 준비작업(거래중인 작업들을 모두 제거하고 이동전 거래가 불가하게 한다)
	MP_NPC_MOVE_MOVENPC_SYN,		// 이동NPC 이동
	MP_NPC_MOVE_MOVENPC_ACK,
	MP_NPC_MOVE_MOVENPC_NACK,
	MP_NPC_ADD_MOVENPC_SYN,			// 이동NPC 추가
	MP_NPC_ADD_MOVENPC_ACK,
	MP_NPC_ADD_MOVENPC_NACK,
	MP_NPC_REMOVE_MOVENPC_SYN,		// 이동NPC 제거
	MP_NPC_REMOVE_MOVENPC_ACK,
	MP_NPC_REMOVE_MOVENPC_NACK,
	// 091015 ONS 스위치역할 NPC 프로토콜 추가
	MP_NPC_SWITCHNPC_SYN,
	MP_NPC_PUT_CHAT_ACK,
};

enum MP_PROTOCOL_QUEST
{
	// Total Info AE¨￢￠￢AU ¡Æ￠®AI￥ia
	MP_QUEST_TOTALINFO,
	MP_QUEST_CHANGESTATE,
	MP_QUEST_REMOVE_NOTIFY,

	// Au¨o¨￢¨¡￠c
	MP_QUEST_MAINDATA_LOAD,
	MP_QUEST_SUBDATA_LOAD,
	MP_QUEST_ITEM_LOAD,

	MP_QUEST_DELETE_SYN,	// Au¨o¨￢¨¡￠c ¨¡¡A¡¾a
	MP_QUEST_DELETE_ACK,
	MP_QUEST_DELETE_NACK,

	MP_QUEST_START_SYN,
	MP_QUEST_START_ACK,
	MP_QUEST_START_NACK,
	MP_QUEST_END_SYN,
	MP_QUEST_END_ACK,
	MP_QUEST_END_NACK,

	MP_SUBQUEST_START_SYN,
	MP_SUBQUEST_START_ACK,
	MP_SUBQUEST_START_NACK,
	MP_SUBQUEST_END_SYN,
	MP_SUBQUEST_END_ACK,
	MP_SUBQUEST_END_NACK,
	MP_SUBQUEST_UPDATE,
	
	MP_QUESTITEM_GIVE,		// questitem
	MP_QUESTITEM_TAKE,
	MP_QUESTITEM_UPDATE,

	MP_QUESTEVENT_NPCTALK,
	
	MP_QUEST_TAKEITEM_ACK,	// item
	MP_QUEST_TAKEMONEY_ACK,	// money
	MP_QUEST_TAKEEXP_ACK,	// exp
	MP_QUEST_TAKESEXP_ACK,	// sexp	
	MP_QUEST_GIVEITEM_ACK,
	MP_QUEST_GIVEMONEY_ACK,
	MP_QUEST_REGIST_CHECKTIME,
	MP_QUEST_UNREGIST_CHECKTIME,
	MP_QUEST_TIME_LIMIT,

	MP_QUESTEVENT_NPCTALK_SYN,
	MP_QUESTEVENT_NPCTALK_ACK,
	MP_QUESTEVENT_NPCTALK_NACK,

	MP_QUEST_EXECUTE_ERROR,
	MP_QUEST_CHANGESTAGE_SYN, 
	MP_QUEST_CHANGESTAGE_ACK, 
	MP_QUEST_CHANGESTAGE_NACK, 

	MP_QUEST_ERROR_EXT,				// 퀘스트 에러 처리를 위한 확장 프로토콜.
	MP_QUEST_ERROR_FULLQUEST,		// 퀘스트 목록이 가득차서 더이상 퀘스트를 진행할 수 없다는 에러를 위한 프로토콜.

	// 071026 LYW --- Protocol : Add protocol.
	MP_QUEST_GIVEITEMS_ACK,
	MP_QUEST_GIVEITEM_ERR,
};

enum MP_PROTOCOL_PK
{
	MP_PK_PKON_SYN,
	MP_PK_PKON_ACK,
	MP_PK_PKON_NACK,

	MP_PK_PKOFF_SYN,
	MP_PK_PKOFF_ACK,
	MP_PK_PKOFF_NACK,
	
	MP_PK_LOOTING_START,
	MP_PK_LOOTING_BEINGLOOTED,

	MP_PK_LOOTING_SELECT_SYN,
	MP_PK_LOOTING_SELECT_ACK,
	MP_PK_LOOTING_SELECT_NACK,

	MP_PK_LOOTING_ITEMLOOTING,		//¨u¨¡AIAU ¨uo=
	MP_PK_LOOTING_ITEMLOOTED,		//¨u¨¡AIAU ¡i?¡¾e

	MP_PK_LOOTING_MOENYLOOTING,
	MP_PK_LOOTING_MOENYLOOTED,

	MP_PK_LOOTING_EXPLOOTING,
	MP_PK_LOOTING_EXPLOOTED,
	
	MP_PK_LOOTING_NOLOOTING,		//¨￢oA¡ⓒ ¨u¡¾AA
	MP_PK_LOOTING_NOINVENSPACE,
	MP_PK_LOOTING_ENDLOOTING,
	MP_PK_DESTROY_ITEM,
	MP_PK_LOOTING_ERROR,	
	MP_PK_DESTROY_SKILL,
	
	MP_PK_PKALLOW_CHANGED,
	MP_PK_DISAPPEAR,

	MP_PK_EXPPENALTY,
	MP_PK_ITEMPENALTY,
};

enum MP_PROTOCOL_HACKCHECK
{
	MP_HACKCHECK_SPEEDHACK,
	MP_HACKCHECK_BAN_USER,
	MP_HACKCHECK_BAN_USER_TOAGENT,	
	// 090109 LUJ, 스크립트 해킹 체크
	MP_HACKCHECK_SCRIPTHACK_SYN,
	MP_HACKCHECK_SCRIPTHACK_ACK,
	MP_HACKCHECK_SCRIPTHACK_NACK,
};

enum MP_PROTOCOL_GUILD
{
	MP_GUILD_CREATE_SYN,
	MP_GUILD_CREATE_ACK,
	MP_GUILD_CREATE_NACK,
	MP_GUILD_CREATE_NOTIFY_TO_MAP,

	MP_GUILD_BREAKUP_SYN,
	MP_GUILD_BREAKUP_ACK,
	MP_GUILD_BREAKUP_NACK,
	MP_GUILD_BREAKUP_NOTIFY_TO_MAP,

	MP_GUILD_ADDMEMBER_SYN,
	MP_GUILD_ADDMEMBER_INVITE,
	MP_GUILD_ADDMEMBER_ACK,
	MP_GUILD_ADDMEMBER_NACK,
	MP_GUILD_ADDMEMBER_NOTIFY_TO_MAP,
	
	MP_GUILD_INVITE,
	MP_GUILD_INVITE_ACCEPT,
	MP_GUILD_INVITE_ACCEPT_NACK,
	MP_GUILD_INVITE_DENY,
	MP_GUILD_INVITE_DENY_NACK,

	MP_GUILD_DELETEMEMBER_SYN,
	MP_GUILD_DELETEMEMBER_ACK,
	MP_GUILD_DELETEMEMBER_NACK,
	MP_GUILD_DELETEMEMBER_NOTIFY_TO_MAP,
	
	MP_GUILD_INFO,
	MP_GUILD_ACCEPT_ACK,
	MP_GUILD_ACCEPT_STUDENT_ACK,

	MP_GUILD_SECEDE_SYN,
	MP_GUILD_SECEDE_ACK,
	MP_GUILD_SECEDE_NACK,
	MP_GUILD_SECEDE_NOTIFY_TO_MAP,
	
	MP_GUILDMARK_REQUEST_SYN,
	MP_GUILDMARK_UPDATE_SYN,
	MP_GUILDMARK_UPDATE_NACK,
	MP_GUILDMARK_REQUEST_ACK,
	MP_GUILDMARK_REQUEST_NACK,

	// 091111 ONS 길드문장 삭제
	MP_GUILDMARK_DEL_SYN,
	MP_GUILDMARK_DEL_ACK,

	MP_GUILDMARK_CHANGE,
	
	MP_GUILDMARK_NOTIFY_TO_MAP,
	
	MP_GUILD_LEVELUP_SYN,	
	//MP_GUILD_LEVELUP_ACK_TO_AGENT,
	//MP_GUILD_LEVELUP_ACK_TO_MAP,
	MP_GUILD_LEVELUP_ACK,
	MP_GUILD_LEVELUP_NACK,
	MP_GUILD_LEVELUP_NOTIFY_TO_MAP,
	
	MP_GUILD_SETENTRYDATE,

	MP_GUILD_CHANGERANK_SYN,
	MP_GUILD_CHANGERANK_ACK,
	MP_GUILD_CHANGERANK_NACK,
	MP_GUILD_CHANGERANK_NOTIFY_TO_MAP,
	
	MP_GUILD_GIVENICKNAME_SYN,
	MP_GUILD_GIVENICKNAME_ACK,
	MP_GUILD_GIVENICKNAME_NACK,
	MP_GUILD_GIVENICKNAME_NOTIFY_TO_MAP,
	MP_GUILD_MEMBERLEVEL_NOTIFY_TO_MAP,
	MP_GUILD_MEMBERLEVEL_NOTIFY, //TO CLIENT
	
	MP_GUILDNAME_CHANGE,
	
	MP_GUILD_LOGINFO,
	MP_GUILD_LOGINFO_NOTIFY_TO_MAP,
	MP_GUILD_NOTE_SYN,
	MP_GUILD_NOTE_ACK,
	MP_GUILD_NOTE_NACK,

	// 06. 03. 문파공지 - 이영준
	MP_GUILD_NOTICE_SYN,
	MP_GUILD_NOTICE_ACK,
	MP_GUILD_NOTICE_NACK,
	MP_GUILD_NOTICE_NOTIFY,

	MP_GUILD_ADDSTUDENT_SYN,
	MP_GUILD_ADDSTUDENT_INVITE,
	MP_GUILD_ADDSTUDENT_ACK,
	MP_GUILD_ADDSTUDENT_NACK,
	MP_GUILD_ADDSTUDENT_NOTIFY_TO_MAP,
	
	MP_GUILD_INVITE_AS_STUDENT,
	MP_GUILD_INVITE_AS_STUDENT_ACCEPT,
	MP_GUILD_INVITE_AS_STUDENT_ACCEPT_NACK,
	MP_GUILD_INVITE_AS_STUDENT_DENY,
	MP_GUILD_INVITE_AS_STUDENT_DENY_NACK,

	MP_GUILD_SCORE_UPDATE_TO_MAP,	// 해당 맵의 길드원에게 점수를 새로 고침한다
	MP_GUILD_SCORE_UPDATE,
	MP_GUILD_SCORE_UPDATE_BY_KILL,	// 다른 길드의 멤버를 죽였을때 길드 포인트를 얻음
	MP_GUILD_SCORE_UPDATE_BY_DEAD,	// 다른 길드의 멤버에게 죽었을때 길드 포인트를 잃음
	MP_GUILD_OPEN_WAREHOUSE_SYN,	// 창고를 연다
	MP_GUILD_OPEN_WAREHOUSE_ACK,	// 창고 열기 승인
	MP_GUILD_OPEN_WAREHOUSE_NACK,	// 창고 열기 거부
	MP_GUILD_CLOSE_WAREHOUSE,		// 창고 닫기
	MP_GUILD_DATA_READ,

	// 창고 접근 권한 설정
	MP_GUILD_SET_WAREHOUSE_RANK_SYN,
	MP_GUILD_SET_WAREHOUSE_RANK_ACK,
	MP_GUILD_SET_WAREHOUSE_RANK_NACK,
	
	MP_GUILD_ITEM_READ,
	MP_GUILD_ITEM_OPTION_READ,
	MP_GUILD_KICED_NOTICE,

	// 070502 LYW --- Protocol : Add protocol to request guild name.
	MP_GUILD_REQUEST_GUILDNAME_SYN,
	MP_GUILD_REQUEST_GUILDNAME_ACK,
	MP_GUILD_REQUEST_GUILDNAME_NACK,
	MP_GUILD_RETIRE_SYN,
	//MP_GUILD_RETIRE_ACK_TO_AGENT,
	MP_GUILD_RETIRE_ACK,
	MP_GUILD_RETIRE_NACK,
	MP_GUILD_CHANGE_MASTER_TO_AGENT,
	//MP_GUILD_CHANGE_MASTER_TO_MAP,
	MP_GUILD_CHANGE_MASTER_TO_USER,

	// 08022 LUJ, 회원 정보가 변경됨
	MP_GUILD_SET_MEMBER_TO_MAP,
	MP_GUILD_SET_MEMBER_ACK,

	// 080417 LUJ, 길드 스킬 정보 전송
	MP_GUILD_GET_SKILL_ACK,
	
	// 080417 LUJ, 길드 스킬 획득
	MP_GUILD_ADD_SKILL_SYN,
	MP_GUILD_ADD_SKILL_ACK,
	MP_GUILD_ADD_SKILL_ACK_TO_MAP,
	MP_GUILD_ADD_SKILL_NACK,

	MP_GUILD_GTOURNAMENT_NOTIFY_TO_MAP,
};

enum MP_PROTOCOL_GUILD_UNION
{
	MP_GUILD_UNION_PLAYER_INFO,
	MP_GUILD_UNION_INFO,

	MP_GUILD_UNION_CREATE_SYN,
	MP_GUILD_UNION_CREATE_ACK,
	MP_GUILD_UNION_CREATE_NACK,
	MP_GUILD_UNION_CREATE_NOTIFY_TO_MAP,

	MP_GUILD_UNION_DESTROY_SYN,
	MP_GUILD_UNION_DESTROY_ACK,
	MP_GUILD_UNION_DESTROY_NACK,
	MP_GUILD_UNION_DESTROY_NOTIFY_TO_MAP,

	MP_GUILD_UNION_INVITE,
	MP_GUILD_UNION_INVITE_WAIT,
	MP_GUILD_UNION_INVITE_NACK,	
	MP_GUILD_UNION_INVITE_ACCEPT,
	MP_GUILD_UNION_INVITE_ACCEPT_NACK,
	MP_GUILD_UNION_INVITE_ACCEPT_NOTIFY_TO_MAP,
	MP_GUILD_UNION_INVITE_DENY,
	MP_GUILD_UNION_INVITE_DENY_NACK,

	MP_GUILD_UNION_ADD_SYN,					// 추가
	MP_GUILD_UNION_ADD_ACK,
	MP_GUILD_UNION_ADD_NACK,
	MP_GUILD_UNION_ADD_NOTIFY_TO_MAP,

	MP_GUILD_UNION_REMOVE_SYN,				// 제명
	MP_GUILD_UNION_REMOVE_ACK,
	MP_GUILD_UNION_REMOVE_NACK,
	MP_GUILD_UNION_REMOVE_NOTIFY_TO_MAP,

	MP_GUILD_UNION_SECEDE_SYN,				// 탈퇴
	MP_GUILD_UNION_SECEDE_ACK,
	MP_GUILD_UNION_SECEDE_NACK,
	MP_GUILD_UNION_SECEDE_NOTIFY_TO_MAP,

	MP_GUILD_UNION_MARK_REGIST_SYN,			// 동맹마크
	MP_GUILD_UNION_MARK_REGIST_ACK,
	MP_GUILD_UNION_MARK_REGIST_NACK,
	MP_GUILD_UNION_MARK_REGIST_NOTIFY_TO_MAP,
	MP_GUILD_UNION_MARK_REQUEST_SYN,
	MP_GUILD_UNION_MARK_REQUEST_ACK,
	MP_GUILD_UNION_MARK_REQUEST_NACK,

	MP_GUILD_UNION_NOTE_SYN,
	MP_GUILD_UNION_NOTE_ACK,
	MP_GUILD_UNION_NOTE_NACK,
};

enum MP_PROTOCOL_GUILD_FIELDWAR
{
	MP_GUILD_WAR_NACK,
	MP_GUILD_WAR_WAIT,	

	MP_GUILD_WAR_DECLARE,
	MP_GUILD_WAR_DECLARE_NACK,
	MP_GUILD_WAR_DECLARE_NACK_BY_UNION,	// 상대가 연합에 속해있는데 마스터 길드가 아닐 경우 길드전을 신청할 수 없다
	MP_GUILD_WAR_DECLARE_ACCEPT,
	MP_GUILD_WAR_DECLARE_DENY,
	MP_GUILD_WAR_DECLARE_DENY_NOTIFY_TOMAP,

	MP_GUILD_WAR_START,
	MP_GUILD_WAR_START_NOTIFY_TOMAP,
	MP_GUILD_WAR_PROC,
	MP_GUILD_WAR_END,
	MP_GUILD_WAR_END_NOTIFY_TOMAP,
	
	MP_GUILD_WAR_SUGGESTEND,
	MP_GUILD_WAR_SUGGESTEND_NOTIFY_TOMAP,	
	MP_GUILD_WAR_SUGGESTEND_NACK,
	MP_GUILD_WAR_SUGGESTEND_ACCEPT,
	MP_GUILD_WAR_SUGGESTEND_ACCEPT_NOTIFY_TOMAP,
	MP_GUILD_WAR_SUGGESTEND_DENY,
	MP_GUILD_WAR_SUGGESTEND_DENY_NOTIFY_TOMAP,

	MP_GUILD_WAR_SURRENDER,
	MP_GUILD_WAR_SURRENDER_NACK,
	MP_GUILD_WAR_SURRENDER_NOTIFY_TOMAP,

	MP_GUILD_WAR_LEVELDOWN,
	
	MP_GUILD_WAR_RECORD,
	MP_GUILD_WAR_ADDMONEY,
	MP_GUILD_WAR_REMOVEMONEY,
	MP_GUILD_WAR_ADDMONEY_TOMAP,
	
	MP_GUILD_WAR_RESULT_TOALLUSER,
};

enum MP_PROTOCOL_GTOURNAMENT
{
	// Regist
	//MP_GTOURNAMENT_REGISTCOUNT,
	MP_GTOURNAMENT_REGIST_SYN,
	MP_GTOURNAMENT_REGIST_ACK,
	MP_GTOURNAMENT_REGIST_NACK,
	MP_GTOURNAMENT_REGISTPLAYER_SYN,
	MP_GTOURNAMENT_REGISTPLAYER_ACK,
	MP_GTOURNAMENT_REGISTPLAYER_NACK,

	MP_GTOURNAMENT_EDITPLAER_SYN,
	MP_GTOURNAMENT_EDITPLAYER_ACK,
	MP_GTOURNAMENT_EDITPLAYER_NACK,
	
	// Can Move to GTMAP
	MP_GTOURNAMENT_MOVETOBATTLEMAP_SYN,
	MP_GTOURNAMENT_MOVETOBATTLEMAP_ACK,
	MP_GTOURNAMENT_MOVETOBATTLEMAP_NACK,

	// Observer Join
	MP_GTOURNAMENT_OBSERVERJOIN_SYN,
	MP_GTOURNAMENT_OBSERVERJOIN_ACK,
	MP_GTOURNAMENT_OBSERVERJOIN_NACK,

	// GuildMember Join
	MP_GTOURNAMENT_BATTLEJOIN_SYN,
	MP_GTOURNAMENT_BATTLEJOIN_ACK,
	MP_GTOURNAMENT_BATTLEJOIN_NACK,

	// Player return to map
	MP_GTOURNAMENT_RETURNTOMAP,					// GTMAP->Player. player return to map
	MP_GTOURNAMENT_LEAVE_SYN,					// Agent->Mapserver. Reload playerinfo when player return to map from GTMAP	
	
	// Standing Info View for Other-player
	MP_GTOURNAMENT_STANDINGINFO_SYN,
	MP_GTOURNAMENT_STANDINGINFO_ACK,			// Only Guild Standing Info
	MP_GTOURNAMENT_STANDINGINFO_NACK,
	MP_GTOURNAMENT_TEAMMEMBER_ADD,
	MP_GTOURNAMENT_TEAMMEMBER_OUT,
	MP_GTOURNAMENT_TEAMMEMBER_DIE,
	MP_GTOURNAMENT_TEAMMEMBER_MORTAL,

	// Observer Out
	MP_GTOURNAMENT_OBSERVER_EXIT,
	MP_GTOURNAMENT_NOTIFY_WINLOSE,
	MP_GTOURNAMENT_NOTIFY,
	MP_GTOURNAMENT_NOTIFY2GUILD,
	MP_GTOURNAMENT_NOTIFY2GUILD_TOMAP,
	MP_GTOURNAMENT_NOTIFY2PLAYER,
	MP_GTOURNAMENT_NOTIFY2PLAYER_TOMAP,

	MP_GTOURNAMENT_REWARD,

	// 091201 ONS 길드 토너먼트 골드보상 추가
	MP_GTOURNAMENT_REWARD_MONEY_TO_MAP,
	MP_GTOURNAMENT_REWARD_MONEY,
	MP_GTOURNAMENT_CHEAT,
	MP_GTOURNAMENT_CHEAT_SETSTATE,
	MP_GTOURNAMENT_CHEAT_GETSTATE_SYN,
	MP_GTOURNAMENT_CHEAT_GETSTATE_ACK,
	MP_GTOURNAMENT_CHEAT_RESET,

	MP_GTOURNAMENT_FORCEREG,
	MP_GTOURNAMENT_FORCEREG_NACK,
};

// 090916 LUJ, 소스 정리 시 누락되었음. 서버툴 사용에 필요함
enum MP_TOOLPROC_CONNECT
{
	MP_RMTOOL_CONNECT_SYN,
	MP_RMTOOL_CONNECT_ACK,
	MP_RMTOOL_CONNECT_NACK,

	MP_CHECKIP_ERROR,
};

// 070228 LYW --- Protocol : Add enum for facial part.
enum MP_PROTOCOL_FACIAL
{
	MP_FACIAL_NORMAL,
} ;

// 070228 LYW --- Protocol : Add enum for emotion part.
enum MP_PROTOCOL_EMOTION
{
	MP_EMOTION_NORMAL,
	// 070501 LYW --- Protocol : Add protocol for sit down and stand up state.
	MP_EMOTION_SITSTAND_SYN,
	MP_EMOTION_SITSTAND_ACK,
	MP_EMOTION_SITSTAND_NACK,

	// 070502 LYW --- Protocol : Add protocol for ing motion.
	MP_EMOTION_ING_MOTION_SYN,
	MP_EMOTION_ING_MOTION_ACK,
	MP_EMOTION_ING_MOTION_NACK,

	// 070528 LYW --- Protocol : Add protocol to play emoticon.
	MP_EMOTICON_SYN,
	MP_PLAY_EMOTICON_ACK,
} ;
//////////////////////////////////////////////////////////////////////////

enum MP_PROTOCOL_FAMILY
{
	MP_FAMILY_CREATE,

	MP_FAMILY_INVITE,
	MP_FAMILY_INVITED,
	MP_FAMILY_INVITE_RESULT,
	MP_FAMILY_INVITE_RESULT_TO_OTHER_AGENT,
	MP_FAMILY_INVITE_RESULT_TO_OTHER_AGENT_2,
	MP_FAMILY_INVITE_RESULT_TO_OTHER_AGENT_3,

	MP_FAMILY_DATA_FAMILY,
	MP_FAMILY_DATA_MEMBER,

	MP_FAMILY_REGIST_EMBLEM,
	MP_FAMILY_REGIST_EMBLEM_TO_OTHER_AGENT,
	MP_FAMILY_SHOW_EMBLEM,
	MP_FAMILY_SHOW_EMBLEM_2,
	// 091111 ONS 패밀리 문장 삭제
	MP_FAMILY_DEL_EMBLEM,
	MP_FAMILY_DEL_EMBLEM_TO_OTHER_AGENT,

	MP_FAMILY_CHANGE_NICKNAME,
	MP_FAMILY_CHANGE_NICKNAME_NACK,
	MP_FAMILY_CHANGE_NICKNAMEON,
	MP_FAMILY_SHOW_NICKNAME,

	MP_FAMILY_HONOR_POINT,
	MP_FAMILY_HONOR_POINT_TO_OTHER_AGENT,

	MP_FAMILY_MEMBER_CONNECTION_TO_OTHER_AGENT,
	MP_FAMILY_UPDATE_MAP_PLAYER_INFO,
	MP_FAMILY_UPDATE_MAP_PLAYER_INFO_TO_OTHER_AGENT,

	MP_FAMILY_LEAVE,
	MP_FAMILY_LEAVE_TO_OTHER_AGENT,
	MP_FAMILY_LEAVE_EMBLEM,

	MP_FAMILY_EXPEL,
	MP_FAMILY_EXPEL_TO_OTHER_AGENT,

	MP_FAMILY_BREAKUP,
	MP_FAMILY_BREAKUP_TO_OTHER_AGENT,

	MP_FAMILY_PENALTY_MSG,
	// 091126 ONS 패밀리장 이양 기능 추가
	MP_FAMILY_TRANSFER,
	MP_FAMILY_TRANSFER_TO_OTHER_AGENT,
	// E 패밀리 추가 added by hseos 2007.07.03		2007.09.27	2007.10.19

	// 090213 LYW --- Protocol : 접속 중인 패밀리 멤버에 따른 추가 기능 처리.
	MP_FAMILY_SETFAMILYID_MAPSERVER,
	MP_FAMILY_REFRESH_FAMILYINFO_MAPSERVER,
	MP_FAMILY_REFRESH_FAMILYINFO_MAPSERVER_OTHER,
	
	// 100809 ONS 클래스초기화 처리시 패밀리 정보를 변경 기능 추가.
	MP_FAMILY_CHANGE_CLASS,
};

enum MP_PROTOCOL_FARM
{
	MP_FARM_FARMSTATE_LOAD_FROM_DB,		// 2007.04.23
	MP_FARM_CROPINFO_LOAD_FROM_DB,		// 2007.04.23
	MP_FARM_BUY,
	MP_FARM_BUY_AGENT_CHECK,			// 2007.09.10
	MP_FARM_GARDEN_PLANT,				// 2007.04.17
	MP_FARM_GARDEN_PLANT_AGENT_CHECK,	// 2007.09.10
	MP_FARM_GARDEN_GROW,				// 2007.04.18
	MP_FARM_GARDEN_MANURE,				// 2007.04.24
	MP_FARM_GARDEN_HARVEST,				// 2007.04.24
	MP_FARM_UPGRADE,					// 2007.09.04
	MP_FARM_UPGRADE_AGENT_CHECK_1,		// 2007.09.10
	MP_FARM_UPGRADE_AGENT_CHECK_2,		// 2007.09.10
	MP_FARM_TIMEDELAY,					// 2007.10.01
	MP_FARM_DEL,						// 2007.10.17
	MP_FARM_DEL_NOTIFY_TO_MEMBER,		// 2008.01.16
    MP_FARM_MANAGE_UI_FARM_DATA,		// 2007.10.26
    MP_FARM_MANAGE_UI_CROP_DATA,		// 2007.10.26
	MP_FARM_PAY_TAX,					// 2008.01.15
	MP_FARM_PAY_TAX_AGENT_CHECK_1,		// 2008.01.15
	MP_FARM_TAX_NONPAYMENT_NOTIFY,		// 2008.01.18
	MP_FARM_ANIMAL_INSTALL,				// 080415 KTH
	MP_FARM_ANIMAL_INSTALL_AGENT_CHECK,	//
	MP_FARM_ANIMALINFO_LOAD_FROM_DB,	// 080417 KTH
	MP_FARM_ANIMAL_GROW,				// 080417 KTH
	MP_FARM_ANIMAL_FEED,				// 080507 KTH
	MP_FARM_ANIMAL_CLEANING,			// 080515 KTH
	MP_FARM_ANIMAL_REWARD,
	// 091204 ONS 패밀리 다이얼로그에 농장세금 납부 기능 추가.
	MP_FARM_SETFARM_CHANGE_OWNER,
	MP_FARM_SETFARM_TAXINFO,
	MP_FARM_SETFARM_TAXINFO_TO_FARMMAP,
	MP_FARM_BUY_RESULT,						// 100219 ONS 농장구입시 패밀리원에게 농장정보를 전달한다
};
// E 농장시스템 추가 added by hseos 2007.04.11

// desc_hseos_주민등록01
// S 주민등록 추가 added by hseos 2007.06.04	2007.11.12	2007.12.31
enum MP_PROTOCOL_RESIDENTREGIST
{
	MP_RESIDENTREGIST_REGIST,
	MP_RESIDENTREGIST_UPDATE_INTRODUCTION,
	MP_RESIDENTREGIST_UPDATE_INTRODUCTION_NACK,

	MP_RESIDENTREGIST_DATEMATCHING_SERCH,
	MP_RESIDENTREGIST_DATEMATCHING_RECOMMEND_OTHER_CHAR,
	MP_RESIDENTREGIST_DATEMATCHING_REQUEST_CHAT,
	MP_RESIDENTREGIST_DATEMATCHING_RESULT_REQUEST_CHAT,
	MP_RESIDENTREGIST_DATEMATCHING_RESULT_START_CHAT,
	MP_RESIDENTREGIST_DATEMATCHING_CHAT,
	MP_RESIDENTREGIST_DATEMATCHING_SOMEBODY_INFO,
	MP_RESIDENTREGIST_DATEMATCHING_SERCH_TO_OTHER_AGENT,
	MP_RESIDENTREGIST_DATEMATCHING_SERCH_TO_OTHER_AGENT_RESULT,
	
	// DIFF_AGENT 는 다른 에이전트의 플레이어와 채팅할 때...
	MP_RESIDENTREGIST_DATEMATCHING_REQUEST_CHAT_DIFF_AGENT,							
	MP_RESIDENTREGIST_DATEMATCHING_REQUEST_CHAT_DIFF_AGENT_TARGET_CHECK,			
	MP_RESIDENTREGIST_DATEMATCHING_REQUEST_CHAT_DIFF_AGENT_TARGET_CHECK_RESULT,
	MP_RESIDENTREGIST_DATEMATCHING_REQUEST_CHAT_DIFF_AGENT_SEND_REQUESTER_INFO,

	MP_RESIDENTREGIST_DATEMATCHING_CHAT_DIFF_AGENT,
	MP_RESIDENTREGIST_DATEMATCHING_RESULT_REQUEST_CHAT_DIFF_AGENT,
	MP_RESIDENTREGIST_DATEMATCHING_RESULT_START_CHAT_DIFF_AGENT,

	MP_RESIDENTREGIST_REGIST_NOTIFY,
	// 100113 ONS 주민등록정보가 변경되었을 경우( 데이트 상대리스트의 클래스가 전직후 업데이트 되도록하기위해.. )
	MP_RESIDENTREGIST_REGIST_CHANGE,
};
// E 주민등록 추가 added by hseos 2007.06.04	2007.11.12	2007.12.31

// 071023 LYW --- Protocol : Add enum code to classification protocil of tutorial part.
enum MP_PROTOCOL_TUTORIAL													// 튜토리얼 프로토콜 분류.
{
	MP_TUTORIAL_MAINDATALOAD,												// 서버에서 로딩한 튜토리얼 정보를 클라인트로 전송하기 위한 프로토콜.

	MP_TUTORIAL_UPDATE_SYN,													// 클라이언트에서 서버로 튜토리얼 완료 요청을 하기 위한 프로토콜.
	MP_TUTORIAL_UPDATE_ACK,													// 서버에서 튜토리얼 완료 성공을 클라이언트로 전송하기 위한 프로토콜.
	MP_TUTORIAL_UPDATE_NACK,												// 서버에서 튜토리얼 완료 실패를 클라이언트로 전송하기 위한 프로토콜.
} ;

// desc_hseos_데이트 존_01
// S 데이트 존 추가 added by hseos 2007.11.16
enum MP_PROTOCOL_DATE
{
	MP_DATE_ENTER_DATEZONE,
	MP_DATE_ENTER_DATEZONE_2,
	MP_DATE_ENTER_CHALLENGEZONE,
	MP_DATE_ENTER_CHALLENGEZONE_2,
	MP_DATE_ENTER_CHALLENGEZONE_3,
	MP_DATE_CHALLENGEZONE_START,
	MP_DATE_CHALLENGEZONE_ENTER_FREQ,
	MP_DATE_CHALLENGEZONE_END_TIMEOUT,
	MP_DATE_CHALLENGEZONE_END_PARTNER_OUT,
	MP_DATE_CHALLENGEZONE_END_ALL_DIE,
	MP_DATE_CHALLENGEZONE_END_SUCCESS,
	MP_DATE_CHALLENGEZONE_RETURN,

	MP_DATE_ENTER_DATEZONE_DIFF_AGENT,
	MP_DATE_ENTER_DATEZONE_2_DIFF_AGENT,
	MP_DATE_ENTER_DATEZONE_2_DIFF_AGENT_CHECK_BATTLE_FOR_OTHER_AGENT, 
	MP_DATE_ENTER_DATEZONE_2_DIFF_AGENT_CHECK_PARTY_FOR_OTHER_AGENT,
	MP_DATE_ENTER_DATEZONE_2_DIFF_AGENT_CHECK_PARTY_FOR_OTHER_AGENT_2,
	MP_DATE_ENTER_DATEZONE_2_DIFF_AGENT_CHECK_PARTY_FOR_OTHER_AGENT_3,

	MP_DATE_ENTER_CHALLENGEZONE_DIFF_AGENT,
	MP_DATE_ENTER_CHALLENGEZONE_2_DIFF_AGENT,
	MP_DATE_ENTER_CHALLENGEZONE_2_DIFF_AGENT_CHECK_BATTLE_FOR_OTHER_AGENT,
	MP_DATE_ENTER_CHALLENGEZONE_2_DIFF_AGENT_CHECK_PARTY_FOR_OTHER_AGENT,
	MP_DATE_ENTER_CHALLENGEZONE_2_DIFF_AGENT_CHECK_PARTY_FOR_OTHER_AGENT_2,
	MP_DATE_ENTER_CHALLENGEZONE_2_DIFF_AGENT_CHECK_PARTY_FOR_OTHER_AGENT_3,
	MP_DATE_ENTER_CHALLENGEZONE_2_DIFF_AGENT_CHECK_PARTY_FOR_OTHER_AGENT_4,
	MP_DATE_ENTER_CHALLENGEZONE_2_DIFF_AGENT_CHECK_PARTY_FOR_OTHER_AGENT_5,
	MP_DATE_ENTER_CHALLENGEZONE_2_DIFF_AGENT_CHECK_PARTY_FOR_OTHER_AGENT_6,
};

//---KES AUTONOTE 2008.1.21
enum MP_PROTOCOL_AUTONOTE
{
	MP_AUTONOTE_ASKTOAUTO_SYN,		//---오토니? 질문하기
	MP_AUTONOTE_ASKTOAUTO_ACK,		//---오토노트 사용 성공
	MP_AUTONOTE_ASKTOAUTO_NACK,		//---오토노트 사용 실패
	MP_AUTONOTE_ASKTOAUTO,			//---오토에게 질문 도착

	MP_AUTONOTE_ANSWER_SYN,			//---질문에 대한 답변
	MP_AUTONOTE_ANSWER_ACK,			//---질문 답변하기 성공
	MP_AUTONOTE_ANSWER_NACK,		//---질문 답변 틀림
	MP_AUTONOTE_ANSWER_FAIL,		//---질문 답변 실패
	MP_AUTONOTE_ANSWER_TIMEOUT,		//---답변 제한시간 초과
	MP_AUTONOTE_ANSWER_LOGOUT,		//---답변없이 접속종료

    MP_AUTONOTE_NOTAUTO,			//---오토가 아님을 알림
	MP_AUTONOTE_KILLAUTO,			//---오토가 킬되었다는 메세지
	MP_AUTONOTE_DISCONNECT,			//---오토유저 접속끊기

	MP_AUTONOTE_LIST_ADD,			//---오토노트 추가
	MP_AUTONOTE_LIST_ALL,			//---오토노트 리스트 보내기

	MP_AUTONOTE_PUNISH,				//---오토노트 사용 금지 기간

	MP_AUTONOTE_ASKTOAUTO_IMAGE,
	// 090108 LUJ, 스크립트를 검사한다
	MP_AUTONOTE_SCRIPT_CHECK_SYN,
	MP_AUTONOTE_SCRIPT_CHECK_NACK,
};
//--------------------------

enum MP_PROTOCAOL_PUNISH
{
	MP_PUNISH_PUNISH,				//---오토노트사용제재중
	MP_PUNISH_COUNT,				//---회수 증가
};

// 080407 LYW --- Protocol : 채팅방 시스템에 필요한 프로토콜 정의.
enum MP_PROTOCOL_CHATROOM
{
	MP_CHATROOM_ADD_USER_SYN,									// 유저 정보 추가 요청.
	MP_CHATROOM_ADD_USER_ACK,									// 유저 정보 추가 성공.
	MP_CHATROOM_ADD_USER_NACK,									// 유저 정보 추가 실패.

	MP_CHATROOM_DEL_USER_SYN,									// 유저 삭제 요청.

	MP_CHATROOM_UPDATE_USERINFO_SYN,							// 유저 정보 업데이트 요청.

	MP_CHATROOM_FORCE_ADD_USER_SYN,								// 강제로 유저 정보 추가 요청.
	MP_CHATROOM_FORCE_ADD_USER_ACK,								// 강제로 유저 정보 추가 성공.
	MP_CHATROOM_FORCE_ADD_USER_NACK,							// 강제로 유저 정보 추가 실패.

	MP_CHATROOM_CHANGE_OPTION_SYN ,								// 채팅방 옵션 변경 요청.
	MP_CHATROOM_CHANGE_OPTION_NACK,								// 채팅방 옵션 변경 실패.
	MP_CHATROOM_CHANGE_OPTION_NOTICE,							// 채팅방 옵션 변경 성공 공지.
	MP_CHATROOM_CHANGE_OPTION_NOTICE_OTHER_AGENT,				// 다른 Agent를 위한 옵션 변경 성공 공지.

	MP_CHATROOM_CHANGE_OWNER_SYN,								// 방장 위임 요청.
	MP_CHATROOM_CHANGE_OWNER_NACK,								// 방장 위임 실패.
	MP_CHATROOM_CHANGE_OWNER_NOTICE,							// 방장 위임 공지.
	MP_CHATROOM_CHANGE_OWNER_NOTICE_OTHER_AGENT,				// 다른 Agent를 위한 방장 위임 공지.

	MP_CHATROOM_CHATMSG_NORMAL_SYN,								// 채팅 메시지 전송 요청.
	MP_CHATROOM_CHATMSG_NORMAL_NACK,							// 채팅 메시지 전송 실패.
	MP_CHATROOM_CHATMSG_NORMAL_NOTICE,							// 채팅 메시지 공지.
	MP_CHATROOM_CHATMSG_NORMAL_NOTICE_OTHER_AGENT,				// 다른 Agent를 위한 메시지 공지.

	MP_CHATROOM_CREATE_ROOM_SYN,								// 채팅방 생성 요청.
	MP_CHATROOM_CREATE_ROOM_ACK,								// 채팅방 생성 성공.
	MP_CHATROOM_CREATE_ROOM_NACK,								// 채팅방 생성 실패.

	MP_CHATROOM_JOIN_ROOM_SYN,									// 채팅방 참여 요청.
	MP_CHATROOM_JOIN_ROOM_ACK,									// 채팅방 참여 성공.
	MP_CHATROOM_JOIN_ROOM_NACK,									// 채팅방 참여 실패.
	MP_CHATROOM_JOIN_ROOM_NOTICE,								// 채팅방 참여 공지.
	MP_CHATROOM_JOIN_ROOM_OTHER_AGENT,							// 다른 Agent를 위한 참여 공지.

	MP_CHATROOM_KICK_GUEST_SYN,									// 강퇴 요청.
	MP_CHATROOM_KICK_GUEST_ACK,									// 강퇴 처리.
	MP_CHATROOM_KICK_GUEST_ACK_OTHER_AGENT,						// 강퇴 처리 다른 에이전트 전송용.
	MP_CHATROOM_KICK_GUEST_NACK,								// 강퇴 실패.
	MP_CHATROOM_KICK_GUEST_NOTICE,								// 강퇴 공지.
	MP_CHATROOM_KICK_GUEST_NOTICE_OTHER_AGENT,					// 다른 Agent를 위한 강퇴 공지.

	MP_CHATROOM_OUT_ROOM_SYN,									// 채팅방 나가기 요청.
	MP_CHATROOM_OUT_ROOM_ACK,									// 채팅방 나가기 성공.
	MP_CHATROOM_OUT_ROOM_NACK,									// 채팅방 나가기 실패.
	MP_CHATROOM_OUT_ROOM_EMPTYROOM,								// 채팅방을 나왔을 때, 더이상 방이 없어서, 클라이언트의 채팅방 리스트를 비우는 처리용.
	MP_CHATROOM_OUT_ROOM_LAST_MAN,								// 마지막으로 방을 나왔을 때, 처리를 하는 함수. ACK와는 구분하여 사용.
	MP_CHATROOM_OUT_ROOM_NOTICE,								// 채팅방 나가기 공지.
	MP_CHATROOM_OUT_ROOM_NOTICE_OTHER_AGENT,					// 다른 Agent를 위한 채팅방 나가기 공지.
	MP_CHATROOM_OUT_ROOM_CHANGE_OWNER_NOTICE,					// 비 정상적인 경우로 방장이 나갔을 경우 공지.
	MP_CHATROOM_OUT_ROOM_CHANGE_OWNER_NOTICE_OTHER_AGENT,		// 다른 Agent를 위한, 방장이 나갔을 경우 공지.

	MP_CHATROOM_REQUEST_FRIEND_SYN,								// 친구 요청.
	MP_CHATROOM_REQUEST_FRIEND_ACK,								// 친구 요청 성공.
	MP_CHATROOM_REQUEST_FRIEND_NACK,							// 친구 요청 실패.

	MP_CHATROOM_ROOM_SYN,										// 채팅방 리스트 요청.
	MP_CHATROOM_ROOMLIST_ACK,									// 채팅방 리스트 성공.
	MP_CHATROOM_ROOMLIST_NACK,									// 채팅방 리스트 실패.

	MP_CHATROOM_SEARCH_FOR_NAME_SYN,							// 이름으로 검색 요청.
	MP_CHATROOM_SEARCH_FOR_NAME_ACK,							// 이름으로 검색 성공.
	MP_CHATROOM_SEARCH_FOR_NAME_NACK,							// 이름으로 검색 실패.

	MP_CHATROOM_SEARCH_FOR_TITLE_SYN,							// 제목으로 검색 요청.
	MP_CHATROOM_SEARCH_FOR_TITLE_ACK,							// 제목으로 검색 성공.
	MP_CHATROOM_SEARCH_FOR_TITLE_NACK,							// 제목으로 검색 실패.

	// 자신의 채팅방과 관련이 없는 다른 채팅방의 변화를 위한 프로토콜들.
	MP_CHATROOM_UPDATEINFO_CREATED_ROOM,						// 채팅방이 추가되었음을 모든 클라이언트에 공지한다.
	MP_CHATROOM_UPDATEINFO_DELETED_ROOM,						// 채팅방이 삭제되었음을 모든 클라이언트에 공지한다.
	MP_CHATROOM_UPDATEINFO_SECRETMODE,							// 채팅방의 공개/비공개가 바뀌었을 때, 이를 모든 클라이언트에 공지한다.
	MP_CHATROOM_UPDATEINFO_ROOMTYPE,							// 채팅방 분류가 바뀌었을 때, 이를 모든 클라이언트에 공지한다.
	MP_CHATROOM_UPDATEINFO_TITLE,								// 채팅방 제목이 바뀌었을 때, 이를 모든 클라이언트에 공지한다.
	MP_CHATROOM_UPDATEINFO_CUR_GUESTCOUNT,						// 채팅방 내, 현재 참여자 수가 바뀜을 모든 클라이언트에 공지한다.
	MP_CHATROOM_UPDATEINFO_TOTAL_GUESTCOUNT,					// 채팅방의 최대 참여자 수가 바뀜을 모든 클라이언트에 공지한다.
} ;

enum MP_PROTOCOL_FISHING
{
	MP_FISHING_READY_SYN,			//---낚시시작요청	C->S
	MP_FISHING_READY_ACK,			//---낚시시작성공	S->C
	MP_FISHING_READY_NACK,			//---낚시시작실패	S->C
	MP_FISHING_CANCEL_SYN,			//---낚시취소요청	C->S		// 무조건취소.
	MP_FISHING_GETFISH_SYN,			//---낚시종료요청	C->S
	MP_FISHING_GETFISH_ACK,			//---낚시종료성공	S->C
	MP_FISHING_GETFISH_NACK,		//---낚시종료실패	S->C
	MP_FISHING_MISSION_UPDATE,		//---낚시미션갱신	S->C
	MP_FISHING_MISSION_REWARD,		//---낚시미션성공	S->C
	MP_FISHING_FPCHANGE_SYN,		//---물고기포인트 변환요청	C->S	FP(FishingPoint : 물고기포인트)
	MP_FISHING_FPCHANGE_ACK,		//---물고기포인트 변환성공 	S->C	FP(FishingPoint : 물고기포인트)
	MP_FISHING_FPCHANGE_NACK,		//---물고기포인트 변환실패 	S->C	FP(FishingPoint : 물고기포인트)

	MP_FISHING_EXP_ACK,				//---숙련도변경통보 S->C
	MP_FISHING_POINT_ACK,			//---포인트변경통보 S->C
	MP_FISHING_LEVELUP_ACK,			//---숙련도렙업통보 S->C
	MP_FISHING_LEVELUP_NACK,
};

enum MP_PROTOCOL_COOK
{
	MP_COOK_SYN,
	MP_COOK_ACK,
	MP_COOK_NACK,

	MP_COOK_STATE,

	MP_COOK_LEVELUP_ACK,
	MP_COOK_LEVELUP_NACK,

	MP_COOK_UPDATERECIPE,

	MP_COOK_CHEAT,
};

enum MP_PROTOCOL_HOUSING
{
	// 하우스생성
	MP_HOUSE_CREATE_SYN,
	MP_HOUSE_CREATE_FROM_SERVER_SYN,
	MP_HOUSE_CREATE_FROM_SERVER_ACK,
	MP_HOUSE_CREATE_ACK,
	MP_HOUSE_CREATE_FROM_SERVER_NACK,
	MP_HOUSE_CREATE_NACK,

	// 하우스입장
	MP_HOUSE_ENTRANCE_SYN, // 성공시 MP_USERCONN_CHANGEMAP_ACK 보냄
	MP_HOUSE_ENTRANCE_FROM_SERVER_SYN,
	MP_HOUSE_ENTRANCE_ACK,
	MP_HOUSE_ENTRANCE_FROM_SERVER_NACK,
	MP_HOUSE_ENTRANCE_NACK,

	//MP_HOUSE_EXIT_SYN,

	// 하우스정보
	MP_HOUSE_INFO_SYN,
	MP_HOUSE_INFO,
	MP_HOUSE_RANKINFO_FORSERVER,
	// 하우스가구목록
	MP_HOUSE_FURNITURELIST,

	// 하우스가구보관
	MP_HOUSE_STORED_SYN,
	MP_HOUSE_STORED_ACK,
	MP_HOUSE_STORED_NACK,

	// 하우스가구보관해제
	MP_HOUSE_RESTORED_SYN,
	MP_HOUSE_RESTORED_ACK,
	MP_HOUSE_RESTORED_NACK,

	// 하우스꾸미기모드
	MP_HOUSE_DECOMODE_SYN,
	MP_HOUSE_DECOMODE_ACK,
	MP_HOUSE_DECOMODE_NACK,

	// 하우스가구설치
	MP_HOUSE_INSTALL_SYN,
	MP_HOUSE_INSTALL_ACK,
	MP_HOUSE_INSTALL_NACK,
	
	// 하우스가구설치해제
	MP_HOUSE_UNINSTALL_SYN,
	MP_HOUSE_UNINSTALL_ACK,		// 시간소진에의한 소멸처리도 이 프로토콜로...
	MP_HOUSE_UNINSTALL_NACK,

	// 하우스가구변경
	MP_HOUSE_UPDATE_SYN,
	MP_HOUSE_UPDATE_ACK,
	MP_HOUSE_UPDATE_NACK,

	// 하우스가구머터리얼변경
	MP_HOUSE_UPDATE_MATERIAL_ACK,

	// 하우스 가구파괴
	MP_HOUSE_DESTROY_SYN,
	MP_HOUSE_DESTROY_ACK,
	MP_HOUSE_DESTROY_NACK,

	// 위치보정을 안하는 강제내리기
	MP_HOUSE_ACTION_FORCE_GETOFF_SYN,
	MP_HOUSE_ACTION_FORCE_GETOFF_ACK,
	MP_HOUSE_ACTION_FORCE_GETOFF_NACK,

	// 하우스액션
	MP_HOUSE_ACTION_SYN,
	MP_HOUSE_ACTION_ACK,
	MP_HOUSE_ACTION_NACK,

	// 하우스보너스
	MP_HOUSE_BONUS_SYN,
	MP_HOUSE_BONUS_ACK,
	MP_HOUSE_BONUS_NACK,

	// 하우스추천
	MP_HOUSE_VOTE_SYN,
	MP_HOUSE_VOTE_ACK,
	MP_HOUSE_VOTE_NACK,

	// 하우스퇴장
	MP_HOUSE_EXIT_SYN,
	MP_HOUSE_EXIT_ACK,
	MP_HOUSE_EXIT_NACK,

	// 하우스추방
	MP_HOUSE_KICK_SYN,
	MP_HOUSE_KICK_ACK,
	MP_HOUSE_KICK_NACK,

	// 하우스관련 통보
	MP_HOUSE_NOTIFY_VISIT,	// 방문
	MP_HOUSE_NOTIFY_EXIT,	// 퇴장
	MP_HOUSE_NOTIFY_ACTION,	// 액션

	// 하우스확장
	MP_HOUSE_EXTEND,
	// 하우스이름변경
	MP_HOUSE_CHANGENAME,

	// 하우스관련 요청실패
	MP_HOUSE_USEITEM_NACK,

	// 치트
	MP_HOUSE_CHEAT_CLOSE_SYN,
	MP_HOUSE_CHEAT_GETINFO_SYN,
	MP_HOUSE_CHEAT_GETINFOALL_ACK,
	MP_HOUSE_CHEAT_GETINFOONE_ACK,
	MP_HOUSE_CHEAT_CALCRANK,

	MP_HOUSE_CHEAT_DELETE_SYN,
	MP_HOUSE_CHEAT_DELETE_SERVER_SYN,
	MP_HOUSE_CHEAT_DELETE_ACK,
	MP_HOUSE_CHEAT_DELETE_NACK,
};

enum MP_PROTOCOL_TRIGGER
{
	MP_TRIGGER_ADDEFFECT_ACK,
	MP_TRIGGER_REMOVEEFFECT_ACK,
	MP_TRIGGER_PLAYSOUND_ACK,
	// 091015 ONS 카메라 관련 프로토콜 추가
	MP_TRIGGER_CAMERA_SHAKE_SYN,
	MP_TRIGGER_CAMERA_SHAKE_ACK,
	MP_TRIGGER_CAMERA_SHAKE_NACK,
	MP_TRIGGER_CAMERA_FILTER_ATTACH,
	MP_TRIGGER_CAMERA_FILTER_DETACH,
	MP_TRIGGER_CAMERA_FILTER_MOVE_ACK,

	MP_TRIGGER_TIMER_START,
	MP_TRIGGER_TIMER_STATE,
	MP_TRIGGER_ANIMATION_BEGIN_ACK,
	MP_TRIGGER_WEATHER_CHANGE_ACK,
	MP_TRIGGER_ENGINE_EFFECT_ACK,
	MP_TRIGGER_COLLISION_TILE_ACK,
	MP_TRIGGER_SELECT_FLAG_ACK,
	MP_TRIGGER_SET_FLAG_SYN,
	MP_TRIGGER_ITEM_OPTION_REQUEST_ACK,
	MP_TRIGGER_ITEM_OPTION_APPLY_SYN,
	MP_TRIGGER_ITEM_OPTION_APPLY_ACK,
	MP_TRIGGER_ADD_SHOCKED_TIME_ACK,
	MP_TRIGGER_DROP_OBJECT_ON_ACK,
	MP_TRIGGER_DROP_OBJECT_OFF_ACK,
};

enum MP_PROTOCOL_DUNGEON
{
	MP_DUNGEON_ENTRANCE_SYN,
	MP_DUNGEON_PORTAL_ENTRANCE_SYN,
	MP_DUNGEON_ENTRANCE_ACK,
	MP_DUNGEON_ENTRANCE_NACK,
	MP_DUNGEON_ENTRANCE_FROM_SERVER_SYN,

	MP_DUNGEON_INFO_SYN,
	MP_DUNGEON_INFO_ACK,
	MP_DUNGEON_INFO_NACK,

	MP_DUNGEON_SETWARP_SYN,
	MP_DUNGEON_SETWARP_ACK,
	MP_DUNGEON_SETWARP_NACK,

	MP_DUNGEON_SETSWITCH_SYN,
	MP_DUNGEON_SETSWITCH_ACK,
	MP_DUNGEON_SETSWITCH_NACK,

	MP_DUNGEON_ZONEBLOCK,
	MP_DUNGEON_ZONEFREE,
	MP_DUNGEON_EDGEBLOCK,
	MP_DUNGEON_EDGEFREE,

	// 091119 ONS 인던무브 메세지 추가
	MP_DUNGEON_FADEMOVE_SYN,
	MP_DUNGEON_FADEMOVE_ACK,
};

enum MP_PROTOCOL_PET
{
	MP_PET_HATCH,

	MP_PET_RECALL_SYN,
	MP_PET_RECALL_ACK,
	MP_PET_RECALL_NACK,

	MP_PET_TARGET_SYN,
	MP_PET_TARGET_ACK,
	MP_PET_TARGET_NACK,

	MP_PET_ATTACK_SYN,
	MP_PET_ATTACK_ACK,
	MP_PET_ATTACK_NACK,

	MP_PET_SKILL_SYN,
	MP_PET_SKILL_ACK,
	MP_PET_SKILL_NACK,

	MP_PET_EXP_NOTIFY,
	MP_PET_LEVELUP_NOTIFY,
	MP_PET_LEVEL_NOTIFY,
	MP_PET_GRADEUP_NOTIFY,
	MP_PET_FRIENDLY_SYNC,

	MP_PET_EVOLUTION_SYN,
	MP_PET_EVOLUTION_ACK,
	MP_PET_EVOLUTION_NACK,

	MP_PET_RESURRECTION_SYN,
	MP_PET_RESURRECTION_ACK,
	MP_PET_AI_SET_SYN,
	MP_PET_AI_SET_ACK,
	MP_PET_AI_SET_NACK,

	MP_PET_LIFE_NOTIFY,			
	MP_PET_MAXLIFE_NOTIFY,

	MP_PET_MANA_NOTIFY,			
	MP_PET_MAXMANA_NOTIFY,
	MP_PET_OBJECT_INFO,
	MP_PET_ITEM_INFO,

	MP_PET_DIE_NOTIFY,

	MP_PET_ITEM_DISCARD_SYN,
	MP_PET_ITEM_DISCARD_ACK,
	MP_PET_ITEM_MOVE_SYN,
	MP_PET_ITEM_MOVE_ACK,
	MP_PET_ITEM_MOVE_NACK,

	MP_PET_ITEM_MOVE_PLAYER_SYN,
	MP_PET_ITEM_MOVE_PLAYER_ACK,
	MP_PET_ITEM_MOVE_PLAYER_NACK,

	// 090625 pdy 펫 기간제 아이템 착용처리 추가
	MP_PET_ITEM_TIMELIMT_ONEMINUTE_FROM_PETINVEN,	//팻인벤에 아이템시간이 1분미만 남았을때..
	// 팻의 HP갱신
	MP_PET_LIFE_BROAD
};

// 080814 KTH --- Protocol : 공성 관련 추가.
enum MP_PROTOCOL_SIEGEWARFARE
{
	// 공성전 지역의 상태를 전송하여 준다.
	MP_SIEGEWARFARE_STATE_SYN,
	MP_SIEGEWARFARE_STATE_ACK,
	MP_SIEGEWARFARE_STATE_NACK,

	// 공성전 관련 메시지를 알리기 위한 프로토콜
	MP_SIEGEWARFARE_NOTIFY,
	MP_SIEGEWARFARE_WATERSEED_COMPLETE,

	MP_SIEGEWARFARE_USE_WATERSEED_SYN,
	MP_SIEGEWARFARE_USE_WATERSEED_ACK,
	MP_SIEGEWARFARE_USE_WATERSEED_NACK,
	MP_SIEGEWARFARE_USE_WATERSEED_CANCEL,
	// 080905 LYW --- Protocol : 워터시드 취소 수락 프로토콜 추가.
	MP_SIEGEWARFARE_USE_WATERSEED_CANCEL_ACK,
	// 080827 LYW --- Protocol : 워터시드의 사용이 완료 되었는지 여부를 확인 할 프로토콜 추가.
	MP_SIEGEWARFARE_ISCOMPLETE_USING_WATERSEED_SYN,

	MP_SIEGEWARFARE_REVIVE_SYN,

	// 080826 KTH -- 공성전 버프 관련
	MP_SIEGEWARFARE_BUFF_SYN,
	MP_SIEGEWARFARE_BUFF_ACK,
	MP_SIEGEWARFARE_BUFF_NACK,

	// 080827 LYW --- Protocol : 공성 상태를 전송하는 프로토콜 추가. ( Player의 맵이동이나, 초기화 시 사용한다.)
	MP_SIEGEWARFARE_SENDSTATE_SYN,

	// 080828 LYW --- Protocol : npc 버프를 요청하는 프로토콜 추가.
	MP_SIEGEWARFARE_REQUEST_NPCBUFFS_SYN,
	MP_SIEGEWARFARE_REQUEST_NPCBUFFS_ACK,
	MP_SIEGEWARFARE_REQUEST_NPCBUFFS_NACK,

	// 080827 LYW --- Protocol : 공성 상태를 변경하는 치트용 프로토콜 추가.
	MP_SIEGEWARFARE_CHEAT_SETSTATE_SYN,

	// 080929 LYW --- Protocol : 깃발사용이 가능한지 체크하는 프로토콜 추가.
	MP_SIEGEWARFARE_CHECK_FLAGUSE_SYN,
	MP_SIEGEWARFARE_CHECK_FLAGUSE_ACK,
	MP_SIEGEWARFARE_CHECK_FLAGUSE_NACK,
	MP_SIEGEWARFARE_CHECK_FLAGUSE_EMPTYMASTER,

	// 080919 LYW --- Protocol : 깃발을 통한 워프 프로토콜 추가.
	MP_SIEGEWARFARE_WARPTOAGIT_SYN,
	MP_SIEGEWARFARE_WARPTOAGIT_ACK,
	MP_SIEGEWARFARE_WARPTOAGIT_NACK,

	// 080922 LYW --- Protocol : 집행위원을 통한 맵이동 프로토콜 추가.
	MP_SIEGEWARFARE_CHANGEMAP_GUILDCOMMITTEE_SYN,
	MP_SIEGEWARFARE_CHANGEMAP_GUILDCOMMITTEE_ACK,
	MP_SIEGEWARFARE_CHANGEMAP_GUILDCOMMITTEE_NACK,

	// 080922 LYW --- Protocol : 던전으로 이동을 요청하는 프로토콜 추가.
	MP_SIEGEWARFARE_MOVETODUNGEON_SYN,
	MP_SIEGEWARFARE_MOVETODUNGEON_ACK,
	MP_SIEGEWARFARE_MOVETODUNGEON_NACK,

	// 081020 LYW --- Protocol : 공성 중, A가 B를 죽였다는 맵 공지 처리용 프로토콜 추가.
	MP_SIEGEWARFARE_NOTICE_KILLANDKILLER_SYN,
	MP_SIEGEWARFARE_NOTICE_KILLANDKILLER_ACK,
	MP_SIEGEWARFARE_NOTICE_KILLANDKILLER_NACK,

	// 081217 LYW --- Protocol : 공성 길드 던전에서 길드 소속 없이 사망시, 캐릭터 선택 화면으로 이동하는 처리 추가.
	MP_SIEGEWARFARE_DIEINGUILDDUNGEON_NOTICE,
	MP_SIEGEWARFARE_WARPVILLAGE_SYN,
};

// 080728 LYW --- Protocol : Ernumerate a protocol for recall part of siege war.
enum MP_SIEGERECALL
{
	MP_SIEGERECALL_EXECUTE_STEP_SYN = 0,
	MP_SIEGERECALL_EXECUTE_STEP_ACK,
	MP_SIEGERECALL_EXECUTE_STEP_NACK,

	MP_SIEGERECALL_ADDOBJ_SYN,
	MP_SIEGERECALL_ADDOBJ_ACK,
	MP_SIEGERECALL_ADDOBJ_NACK,


	MP_SIEGERECALL_ADDCHECKOBJDIE_SYN,
	MP_SIEGERECALL_ADDCHECKOBJDIE_ACK,
	MP_SIEGERECALL_ADDCHECKOBJDIE_NACK,


	MP_SIEGERECALL_USEITEM_SYN,
	MP_SIEGERECALL_USEITEM_ACK,
	MP_SIEGERECALL_USEITEM_NACK,


	MP_SIEGERECALL_ADDCOMMAND_SYN,
	MP_SIEGERECALL_ADDCOMMAND_ACK,
	MP_SIEGERECALL_ADDCOMMAND_NACK,


	MP_SIEGERECALL_NOTICE_DIERECALLOBJ_READY_SYN,
	MP_SIEGERECALL_NOTICE_DIERECALLOBJ_READY_ACK,
	MP_SIEGERECALL_NOTICE_DIERECALLOBJ_READY_NACK,


	MP_SIEGERECALL_REMOVE_ALLMAP_OBJ_SYN,
	MP_SIEGERECALL_REMOVE_ALLMAP_OBJ_ACK,
	MP_SIEGERECALL_REMOVE_ALLMAP_OBJ_NACK,

	MP_SIEGERECALL_NOTICE_REMOVE_ALLMAP_ALLOBJ_SYN,
	MP_SIEGERECALL_NOTICE_REMOVE_ALLMAP_ALLOBJ_ACK,
	MP_SIEGERECALL_NOTICE_REMOVE_ALLMAP_ALLOBJ_NACK,

	MP_SIEGERECALL_NOTICE_REMOVE_ALLMAP_SPECIFYOBJ_SYN,
	MP_SIEGERECALL_NOTICE_REMOVE_ALLMAP_SPECIFYOBJ_ACK,
	MP_SIEGERECALL_NOTICE_REMOVE_ALLMAP_SPECIFYOBJ_NACK,


	MP_SIEGERECALL_REMOVE_SPECIFYMAP_OBJ_SYN,
	MP_SIEGERECALL_REMOVE_SPECIFYMAP_OBJ_ACK,
	MP_SIEGERECALL_REMOVE_SPECIFYMAP_OBJ_NACK,

	MP_SIEGERECALL_NOTICE_REMOVE_SPECIFYMAP_ALLOBJ_SYN,
	MP_SIEGERECALL_NOTICE_REMOVE_SPECIFYMAP_ALLOBJ_ACK,
	MP_SIEGERECALL_NOTICE_REMOVE_SPECIFYMAP_ALLOBJ_NACK,

	MP_SIEGERECALL_NOTICE_REMOVE_SPECIFYMAP_SPECIFYOBJ_SYN,
	MP_SIEGERECALL_NOTICE_REMOVE_SPECIFYMAP_SPECIFYOBJ_ACK,
	MP_SIEGERECALL_NOTICE_REMOVE_SPECIFYMAP_SPECIFYOBJ_NACK,


	MP_SIEGERECALL_REQUEST_OBJINFO_SYN,
	MP_SIEGERECALL_REQUEST_OBJINFO_ACK,
	MP_SIEGERECALL_REQUEST_OBJINFO_NACK,

	// 081007 LYW --- Protocol : 해당맵의 소환물이 몇개여야 하는지 요청관련 프로토콜 추가.
	MP_SIEGERECALL_REQUEST_RECALLCOUNT_SYN,
	MP_SIEGERECALL_REQUEST_RECALLCOUNT_ACK,
	MP_SIEGERECALL_REQUEST_RECALLCOUNT_NACK,

	// 081015 LYW --- Protocol : 해당맵의 소환물 정보가 몇개인지, 맵 서버 로딩시 알려주는 프로토콜 추가.
	MP_SIEGERECALL_LOAD_RECALLCOUNT_SYN,
	MP_SIEGERECALL_LOAD_RECALLCOUNT_ACK,
	MP_SIEGERECALL_LOAD_RECALLCOUNT_NACK,


	MP_SIEGE_CHEAT_EXECUTE_STEP_SYN,
	MP_SIEGE_CHEAT_EXECUTE_STEP_ACK,
	MP_SIEGE_CHEAT_EXECUTE_STEP_NACK,

	MP_SIEGE_CHEAT_REMOVE_ALLMAP_ALLOBJ_SYN,
	MP_SIEGE_CHEAT_REMOVE_ALLMAP_ALLOBJ_ACK,
	MP_SIEGE_CHEAT_REMOVE_ALLMAP_ALLOBJ_NACK,

	MP_SIEGE_CHEAT_REMOVE_ALLMAP_SPECIFYOBJ_SYN,
	MP_SIEGE_CHEAT_REMOVE_ALLMAP_SPECIFYOBJ_ACK,
	MP_SIEGE_CHEAT_REMOVE_ALLMAP_SPECIFYOBJ_NACK,

	MP_SIEGE_CHEAT_REMOVE_SPECIFYMAP_ALLOBJ_SYN,
	MP_SIEGE_CHEAT_REMOVE_SPECIFYMAP_ALLOBJ_ACK,
	MP_SIEGE_CHEAT_REMOVE_SPECIFYMAP_ALLOBJ_NACK,

	MP_SIEGE_CHEAT_REMOVE_SPECIFYMAP_SPECIFYOBJ_SYN,
	MP_SIEGE_CHEAT_REMOVE_SPECIFYMAP_SPECIFYOBJ_ACK,
	MP_SIEGE_CHEAT_REMOVE_SPECIFYMAP_SPECIFYOBJ_NACK,

	// 081011 LYW --- Protocol : 소환 상태를 다음 단계로 넘기는 치트 관련 추가.
	MP_SIEGE_CHEAT_NEXTSTEP_SYN,
	MP_SIEGE_CHEAT_NEXTSTEP_ACK,
	MP_SIEGE_CHEAT_NEXTSTEP_NACK,
	MP_SIEGE_CHEAT_NEXTSTEP_OTHER_AGENT_SYN,

	MP_SIEGE_CHEAT_ENDSTEP_SYN,
	MP_SIEGE_CHEAT_ENDSTEP_ACK,
	MP_SIEGE_CHEAT_ENDSTEP_NACK,
	MP_SIEGE_CHEAT_ENDSTEP_OTHER_AGENT_SYN,

} ;

// 080819 LYW --- Add a category for recall npc.
enum MP_RECALLNPC
{
	MP_RECALLNPC_CTOM_RECALL_SYN,
	MP_RECALLNPC_MTOC_RECALL_ACK,
	MP_RECALLNPC_MTOC_RECALL_NACK,
	MP_RECALLNPC_MTOC_ALREADY_RECALL_NACK,

	MP_RECALLNPC_MTOA_LOADNPC_SYN,


	MP_RECALLNPC_CTOAM_CHANGEMAP_SYN,
	MP_RECALLNPC_ATOC_CHANGEMAP_NACK,
	MP_RECALLNPC_MTOC_CHANGEMAP_NACK,
	MP_RECALLNPC_MTOA_CHANGEMAP_SYN,
	MP_RECALLNPC_ATOM_CHANGEMAP_ACK,
	MP_RECALLNPC_MTOA_CHANGEMAP_NACK,

	MP_RECALLNPC_MTOA_MAP_OUT,


	MP_RECALLNPC_CHEAT_RECALL_SYN,
} ;

// 091106 LUJ, 리미트 던젼 프로토콜 정리
enum MP_PROTOCOL_LIMITDUNGEON
{
	MP_LIMITDUNGEON_JOIN_SYN,
	MP_LIMITDUNGEON_JOIN_ACK,
	MP_LIMITDUNGEON_JOIN_NACK,
	MP_LIMITDUNGEON_SET_STATUS_ACK,
};

// 090422 ShinJS --- 탈것 추가
enum MP_PROTOCOL_VEHICLE
{
	MP_VEHICLE_SUMMON_SYN,
	MP_VEHICLE_SUMMON_ACK,
	MP_VEHICLE_SUMMON_NACK,
	// 090316 LUJ, 소환 해제
	MP_VEHICLE_UNSUMMON_SYN,
	MP_VEHICLE_UNSUMMON_ACK,
	MP_VEHICLE_UNSUMMON_NACK,
	// 090316 LUJ, 승차 요청
	MP_VEHICLE_MOUNT_ASK_SYN,
	MP_VEHICLE_GET_OPTION_SYN,
	MP_VEHICLE_GET_OPTION_ACK,
	MP_VEHICLE_MOUNT_REQUEST_SYN,
	MP_VEHICLE_MOUNT_REQUEST_ACK,
	MP_VEHICLE_MOUNT_REQUEST_NACK,
	// 090316 LUJ, 승차 요청에 대한 응답
	MP_VEHICLE_MOUNT_ALLOW_SYN,
	MP_VEHICLE_MOUNT_ALLOW_ACK,
	MP_VEHICLE_MOUNT_REJECT_SYN,
	MP_VEHICLE_MOUNT_REJECT_ACK,
	// 090316 LUJ, 하차
	MP_VEHICLE_DISMOUNT_SYN,
	MP_VEHICLE_DISMOUNT_ACK,
	MP_VEHICLE_ERROR_ACK,
	// 090316 LUJ, 탑승 정보 갱신
	MP_VEHICLE_PASSENGER_ACK,
};

// 091230 ShinJS --- PC방 프로토콜 추가
enum MP_PROTOCOL_PCROOM
{
	MP_PCROOM_CONNECT_INFO,				// PC방 접속 정보
	MP_PCROOM_PROVIDE_ITEM_SYN,			// 아이템 지급
	MP_PCROOM_PROVIDE_ITEM_ACK,
	MP_PCROOM_PROVIDE_ITEM_NACK,
	MP_PCROOM_OPEN_MALL_SYN,			// PC방 Mall Open
	MP_PCROOM_OPEN_MALL_ACK,
	MP_PCROOM_OPEN_MALL_NACK,
	MP_PCROOM_CLOSE_MALL,				// PC방 Mall Close
	MP_PCROOM_CHANGE_POINT,				// PC방 POINT 변경

	//100118 ONS 친구관리 다이얼로그에 PC방정보관련 기능추가
	MP_PCROOM_INFO_SYN,
	MP_PCROOM_INFO_ACK,
	// 100312 ONS 다른 맵서버로 PC방 버프정보 전송 프로토콜 추가.
	MP_PCROOM_INFO_SYN_OTHERMAP,		 
	MP_PCROOM_UPDATE_PARTYBUFF_OTHERMAP,
	MP_PCROOM_SETMEMBER_COUNT_OTHERMAP,
	MP_PCROOM_PROVIDE_DAILYBUFF,		
	MP_PCROOM_PROVIDE_PARTYBUFF,
};

// 100510 NYJ - 판매대행 프로토콜
enum MP_PROTOCOL_CONSIGNMENT
{
	MP_CONSIGNMENT_GETLIST_SYN,
	MP_CONSIGNMENT_GETLIST_ACK,
	MP_CONSIGNMENT_GETLIST_NACK,

	MP_CONSIGNMENT_REGIST_SYN,
	MP_CONSIGNMENT_REGIST_ACK,
	MP_CONSIGNMENT_REGIST_NACK,

	MP_CONSIGNMENT_SEARCH_SYN,
	MP_CONSIGNMENT_SEARCHINDEX_SYN,
	MP_CONSIGNMENT_SEARCH_ACK,
	MP_CONSIGNMENT_SEARCH_NACK,

	MP_CONSIGNMENT_UPDATE_SYN,
	MP_CONSIGNMENT_UPDATE_ACK,
	MP_CONSIGNMENT_UPDATE_NACK,
	MP_CONSIGNMENT_UPDATE_PARTBUY,
};

#endif // __PROTOCOL_H__
