//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LunaGameDataExtracter.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LUNAGAMEDATAEXTRACTER_DIALOG 102
#define IDD_DIALOG_EXTRACT_OPT          129
#define IDR_MAINFRAME                   130
#define IDC_PICTURE                     1000
#define IDC_BUTTON_EXTRACT              1001
#define IDC_PROGRESS_CTRL               1002
#define IDC_STATIC_PROGRESS_STATUS      1004
#define IDC_BUTTON_SCRIPT_RELOAD        1005
#define IDC_CHECK_2DITEM_ICON_IMAGE     1006
#define IDC_CHECK_3DMONSTER_IMAGE       1007
#define IDC_CHECK_2DITEM_ICON_IMAGE_ALL 1008
#define IDC_EDIT_2DITEM_ICON_IMAGE_RANGE_MIN 1009
#define IDC_EDIT_2DITEM_ICON_IMAGE_RANGE_MAX 1010
#define IDC_CHECK_3DMONSTER_IMAGE_ALL   1011
#define IDC_EDIT_3DMONSTER_IMAGE_RANGE_MIN 1012
#define IDC_EDIT_3DMONSTER_IMAGE_RANGE_MAX 1013
#define IDC_CHECK_2DACTIVESKILL_IMAGE   1014
#define IDC_CHECK_2DACTIVESKILL_IMAGE_ALL 1015
#define IDC_EDIT_2DACTIVESKILL_IMAGE_RANGE_MIN 1016
#define IDC_EDIT_2DACTIVESKILL_IMAGE_RANGE_MAX 1017
#define IDC_CHECK_IDC_EDIT_2DBUFFSKILL_IMAGE 1018
#define IDC_CHECK_2DBUFFSKILL_IMAGE_ALL 1019
#define IDC_EDIT_2DBUFFSKILL_IMAGE_RANGE_MIN 1020
#define IDC_EDIT_2DBUFFSKILL_IMAGE_RANGE_MAX 1021
#define IDC_CHECK_ITEM_DATA             1022
#define IDC_CHECK_EXTRACT_FILE_TEXT     1023
#define IDC_CHECK_EXTRACT_FILE_EXCEL    1024
#define IDC_CHECK_MONSTER_DATA          1025
#define IDC_CHECK_SKILL_DATA            1026
#define IDC_CHECK_QUEST_DATA            1027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
