//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define MANIFEST_RESOURCE_ID            1
#define IDD_GMDIALOG                    103
#define IDD_GM_MOVE_DIALOG              104
#define IDD_GM_WHERE_DIALOG             105
#define IDD_GM_ITEM_DIALOG              106
#define IDD_GM_HIDE_DIALOG              107
#define IDD_GM_CHAT_DIALOG              108
#define IDD_GM_DISCON_DIALOG            110
#define IDD_GM_BLOCK_DIALOG             111
#define IDD_GM_REGEN_DIALOG             112
#define IDD_GM_PK_DIALOG                113
#define IDI_GAMEICON                    114
#define IDD_GM_COUNSEL_DIALOG           114
#define IDD_GMLOGIN                     115
#define IDD_GM_NOTICE_DIALOG            116
#define IDC_CURSOR_DEFAULT              117
#define IDD_GM_EVENT_DIALOG             117
#define IDC_CURSOR_ATTACK               118
#define IDD_GM_EVENTMAP_DIALOG          118
#define IDC_CURSOR_SELECT               119
#define IDD_GM_EVENTNOTIFY_DIALOG       119
#define IDC_CURSOR_CANTMOVE             120
#define IDC_CURSOR_SPEECH               121
#define IDC_CURSOR_DOT                  122
#define IDD_DIALOG1                     125
#define IDD_GM_WEATHER                  127
#define IDD_GM_WEATHER_DIALOG           127
#define IDD_GM_MAPCHANGE_HIDE_DIALOG    128
#define IDD_TSDIALOG                    128
#define IDD_TS_ITEM_DIALOG              129
#define IDD_TS_CHAR_DIALOG              130
#define IDD_TS_MOVE_DIALOG              131
#define IDD_TS_REGEN_DIALOG             132
#define IDD_TS_OUTPUT_DIALOG            133
#define IDD_TS_QUEST_DIALOG             134
#define IDD_TS_WEATHER_DIALOG           135
#define IDD_GM_DUNGEON_DIALOG           136
#define IDC_GMMOVE_BTN_ME               1014
#define IDC_GMMOVE_BTN_USER             1015
#define IDC_GMMOVE_BTN_XY               1016
#define IDC_GMMOVE_BTN_NAME             1017
#define IDC_GMMOVE_BTN_MAP              1018
#define IDC_GMMOVE_EDT_X                1019
#define IDC_GMMOVE_EDT_Y                1020
#define IDC_GMMOVE_EDT_NAME             1021
#define IDC_GMMOVE_EDT_MAP              1022
#define IDC_GMMOVE_BTN_NPC              1022
#define IDC_GMMOVE_OK                   1023
#define IDC_GM_MNBTN_MOVE               1024
#define IDC_GMMOVE_CANCEL               1024
#define IDC_GM_MNBTN_WHERE              1025
#define IDC_GMMOVE_EDT_USER             1025
#define IDC_GMCHAT_BTN_USER             1025
#define IDC_GM_MNBTN_ITEM               1026
#define IDC_GMCHAT_BTN_MAP              1026
#define IDC_GMMOVE_EDT_CHANNEL          1026
#define IDC_GMCHAT_BTN_REASON           1026
#define IDC_GM_MNBTN_HIDE               1027
#define IDC_GMCHAT_EDT_USER             1027
#define IDC_GMMOVE_EDT_NPC              1027
#define IDC_GMMOVE_CMB_NPC              1027
#define IDC_GMCHAT_BTN_APPLY            1028
#define IDC_GMMOVE_BTN_MINIMAP          1028
#define IDC_GMCHAT_EDT_REASON           1028
#define IDC_GM_MNBTN_PK                 1029
#define IDC_GMCHAT_BTN_NOCHAT           1029
#define IDC_GMCHAT_BTN_FORBID           1029
#define IDC_GM_MNBTN_DISCON             1030
#define IDC_GMCHAT_BTN_ALLOW            1030
#define IDC_GM_MNBTN_BLOCK              1031
#define IDC_GMCHAT_BTN_CANCEL           1031
#define IDC_GM_MNBTN_FORBIDCHAT         1031
#define IDC_GM_MNBTN_REGEN              1032
#define IDC_GMCHAT_EDT_TIME             1032
#define IDC_GMCHAT_BTN_AUTO             1032
#define IDC_GMCHAT_EDT_MAP              1033
#define IDC_GMCHAT_BTN_MANUAL           1033
#define IDC_GM_MNBTN_COUNSEL            1033
#define IDC_GMCHAT_BTN_INFO             1034
#define IDC_GMCHAT_BTN_LOOKUP           1034
#define IDC_GM_MNBTN_NOTICE             1034
#define IDC_GMCHAT_BTN_PERMIT           1034
#define IDC_GM_MNBTN_EVENT              1035
#define IDC_GMDISCON_EDT_CHAR           1036
#define IDC_GM_MNBTN_EVENT1             1036
#define IDC_GM_MNBTN_EVENT1_ON          1036
#define IDC_GM_MNBTN_EVENTMAP           1036
#define IDC_GMDISCON_BTN_DISCON         1037
#define IDC_GM_MNBTN_EVENT1_OFF         1037
#define IDC_GM_MNBTN_EVENTNOTIFY        1037
#define IDC_GMBLOCK_EDT_CHAR            1038
#define IDC_GM_MNBTN_WEATHER            1038
#define IDC_GM_MNBTN_MAPCHANGE_HIDE     1039
#define IDC_GMBLOCK_BTN_APPLY           1039
#define IDC_GMREGEN_EDT_Y               1039
#define IDC_GM_MNBTN_DUNGEON            1039
#define IDC_GM_MNBTN_NONE               1040
#define IDC_GMBLOCK_BTN_BLOCK           1040
#define IDC_GMREGEN_BTN_APPLY           1040
#define IDC_GMBLOCK_BTN_UNBLOCK         1041
#define IDC_GMREGEN_EDT_RAD             1041
#define IDC_GMBLOCK_TIME_TIME           1042
#define IDC_GMBLOCK_DATE_DATE           1043
#define IDC_GMBLOCK_BTN_CANCEL          1044
#define IDC_GMBLOCK_BTN_USER            1045
#define IDC_GMHIDE_BTN_ME               1046
#define IDC_GMHIDE_BTN_USER             1047
#define IDC_GMHIDE_BTN_NPC              1048
#define IDC_GMHIDE_EDT_USER             1049
#define IDC_GMHIDE_BTN_HIDE             1050
#define IDC_GMHIDE_BTN_SHOW             1051
#define IDC_GMHIDE_BTN_APPLY            1052
#define IDC_GMHIDE_BTN_CANCEL           1053
#define IDC_GMWHERE_BTN_USER            1053
#define IDC_GMWHERE_EDT_USER            1054
#define IDC_GMWHERE_BTN_WHERE           1055
#define IDC_GMWHERE_BTN_CANCEL          1056
#define IDC_GMWHERE_EDT_MAP             1057
#define IDC_GMWHERE_EDT_X               1058
#define IDC_GMWHERE_EDT_Y               1059
#define IDC_GMWHERE_BTN_MAP             1060
#define IDC_GMITEM_BTN_ITEM             1060
#define IDC_GMWHERE_BTN_XY              1061
#define IDC_GMITEM_BTN_MONEY            1061
#define IDC_GMITEM_BTN_GET              1062
#define IDC_GMWHERE_EDT_CHANNEL         1062
#define IDC_GMITEM_BTN_CANCEL           1063
#define IDC_GMITEM_EDT_MONEY            1064
#define IDC_GMITEM_CMB_ITEM             1065
#define IDC_GMITEM_BTN_POTION           1066
#define IDC_GMITEM_BTN_WEAPON           1067
#define IDC_GMITEM_BTN_CLOTHES          1068
#define IDC_GMITEM_CMB_POTION           1069
#define IDC_GMREGEN_CMB_MOBNAME         1070
#define IDC_GMITEM_CMB_WEAPON           1070
#define IDC_GMREGEN_EDT_MOBNUM          1071
#define IDC_GMITEM_CMB_CLOTHES          1071
#define IDC_GMREGEN_CMB_MAP             1072
#define IDC_GMITEM_BTN_SKILL            1072
#define IDC_GMREGEN_CMB_ITEM1           1073
#define IDC_GMREGEN_CMB_ITEM            1073
#define IDC_GMITEM_CMB_SKILL            1073
#define IDC_GMREGEN_EDT_X               1074
#define IDC_GMITEM_BTN_ABILITY          1074
#define IDC_GMITEM_BTN_SKILLPOINT       1074
#define IDC_GMREGEN_EDT_RANGE           1075
#define IDC_GMITEM_EDT_ABILITY          1075
#define IDC_GMITEM_EDT_SKILLPOINT       1075
#define IDC_GMREGEN_BTN_MYPOS           1076
#define IDC_GMITEM_BTN_SKILLBOOK        1076
#define IDC_GMREGEN_EDT_ITEM1           1077
#define IDC_GMREGEN_EDT_ITEM            1077
#define IDC_GMITEM_CMB_SKILLBOOK        1077
#define IDC_GMITEM_BTN_ETC              1078
#define IDC_GMITEM_CMB_ETC              1079
#define IDC_GMITEM_BTN_ACCESSORY        1080
#define IDC_GMITEM_CMB_ACCESSORY        1081
#define IDC_GMREGEN_BTN_MODEDIRECT      1082
#define IDC_GMITEM_BTN_SEARCH           1082
#define IDC_GMREGEN_BTN_MODEFILE        1083
#define IDC_GMREGEN_BTN_DELETE          1084
#define IDC_GMREGEN_BTN_CANCEL          1085
#define IDC_GMMOVE_CMB_MAP              1086
#define IDC_GMREGEN_EDT_FILE            1087
#define IDC_GMMOVE_CMB_CHANNEL          1087
#define IDC_GMREGEN_BTN_OPEN            1088
#define IDC_GMREGEN_CMB_CHANNEL         1089
#define IDC_GMITEM_EDT_POTION           1090
#define IDC_GMITEM_EDT_ETC              1091
#define IDC_GMITEM_SPN_POTION           1093
#define IDC_GMITEM_CMB_WEAPONGRADE      1094
#define IDC_GMITEM_CMB_CLOTHESGRADE     1095
#define IDC_GMITEM_CMB_SKILLSUNG        1096
#define IDC_GMDISCON_BTN_USER           1096
#define IDC_GMITEM_SPN_ETC              1097
#define IDC_GMDISCON_BTN_MAP            1097
#define IDC_GMDISCON_CMB_MAP            1098
#define IDC_GMDISCON_BTN_APPLY          1099
#define IDC_GMDISCON_BTN_CANCEL         1100
#define IDC_GMDISCON_BTN_EXCEPTSELF     1101
#define IDC_GMCHAT_CMB_MAP              1102
#define IDC_GMCHAT_DATE_DATE            1103
#define IDC_GMCHAT_TIME_TIME            1104
#define IDC_GMCHAT_CMB_CHANNEL          1105
#define IDC_GMPK_BTN_MAP                1106
#define IDC_GMPK_CMB_MAP                1107
#define IDC_GMPK_CMB_CHANNEL            1108
#define IDC_GMPK_BTN_NOPK               1109
#define IDC_GMPK_BTN_ALLOW              1110
#define IDC_GMPK_BTN_APPLY              1111
#define IDC_GMPK_BTN_CANCEL             1112
#define IDC_GMBLOCK_BTN_AUTO            1113
#define IDC_GMBLOCK_BTN_MANUAL          1114
#define IDC_GMBLOCK_BTN_LOOKUP          1115
#define IDC_GMCOUNSEL_EDT_CHAT          1116
#define IDC_TSOUTPUT_EDIT               1116
#define IDC_GMCOUNSEL_EDT_INPUT         1118
#define IDC_GMCOUNSEL_CMB_ID            1119
#define IDC_GMCOUNSEL_BTN_SAVE          1120
#define IDC_GMLOGIN_EDT_ID              1121
#define IDC_GMLOGIN_EDT_PW              1122
#define IDC_GMLOGIN_BTN_CANCEL          1124
#define IDC_GMLOGIN_BTN_CONNECT         1125
#define IDC_GMNOTICE_BTN_ALLMAP         1126
#define IDC_GMNOTICE_CMB_MAP            1127
#define IDC_GMNOTICE_OK                 1128
#define IDC_GMNOTICE_EDT_NOTICE         1129
#define IDC_GMNOTICE_BTN_MAP            1130
#define IDC_GMNOTICE_CANCEL             1131
#define IDC_GMNOTICE_EDT_PREFACE        1132
#define IDC_GMEVENT_BTN_APPLY           1132
#define IDC_GMEVENT_BTN_CLOSE           1133
#define IDC_GMEVENT_CMB_EVENT           1134
#define IDC_GMEVENT_EDT_RATE            1135
#define IDC_GMEVENTMAP_BTN_SEND         1136
#define IDC_GMEVENT_BTN_AUTO_ON         1136
#define IDC_GMEVENTMAP_BTN_USER         1137
#define IDC_GMEVENTNOTIFY_BTN_OFF       1137
#define IDC_GMEVENT_BTN_AUTO_OFF        1137
#define IDC_GMEVENTMAP_EDT_CHAR         1138
#define IDC_GMEVENTMAP_BTN_CHNANNEL     1139
#define IDC_GMEVENTMAP_EDT_CHANNEL      1140
#define IDC_GMEVENTNOTIFY_EDT_CONTEXT   1140
#define IDC_GMEVENTMAP_BTN_TEAM         1141
#define IDC_GMEVENTMAP_EDT_TEAM         1142
#define IDC_GMEVENTMAP_BTN_CLOSE        1143
#define IDC_GMEVENTMAP_BTN_STARTEVENT   1144
#define IDC_GMEVENTMAP_BTN_CHNANNEL2    1145
#define IDC_GMEVENTMAP_EDT_CHANNEL2     1146
#define IDC_GMEVENTNOTIFY_BTN_ON        1150
#define IDC_GMEVENTNOTIFY_EDT_TITLE     1151
#define IDC_GMEVENTNOTIFY_BTN_CLOSE     1152
#define IDC_GMEVENTNOTIFY_BTN_SOUND1    1153
#define IDC_GMEVENTNOTIFY_BTN_SOUND2    1154
#define IDC_GMEVENTNOTIFY_BTN_SOUND3    1155
#define IDC_GMEVENTNOTIFY_BTN_SOUND     1157
#define IDC_GMEVENTNOTIFY_BTN_PLAYSOUND 1158
#define IDC_GMEVENTNOTIFY_BTN_NOTIFY    1160
#define IDC_GMWEATHER_BTN_APPLY         1162
#define IDC_GMWEATHER_BTN_CANCEL        1163
#define IDC_GMWEATHER_CMB_STARTTIME1    1164
#define IDC_GMWEATHER_CMB_SPENDTIME1    1165
#define IDC_GMWEATHER_CMB_KIND1         1166
#define IDC_GMWEATHER_CMB_STARTTIME2    1167
#define IDC_GMWEATHER_CMB_SPENDTIME2    1168
#define IDC_GMWEATHER_CMB_KIND2         1169
#define IDC_GMWEATHER_CMB_STARTTIME3    1170
#define IDC_GMWEATHER_CMB_SPENDTIME3    1171
#define IDC_GMWEATHER_CMB_KIND3         1172
#define IDC_GMWEATHER_CMB_STARTTIME4    1173
#define IDC_GMWEATHER_CMB_SPENDTIME4    1174
#define IDC_GMWEATHER_CMB_KIND4         1175
#define IDC_GMWEATHER_BTN_START         1176
#define IDC_GMWEATHER_BTN_STOP          1177
#define IDC_GMWEATHER_CMB_KIND_NOW      1178
#define IDC_GMWEATHER_CMB_KIND          1178
#define IDC_GMWEATHER_CMB_MAP           1179
#define IDC_GMWEATHER_CMB_KIND_EXE      1180
#define IDC_GMWEATHER_BTN_MAP           1181
#define IDC_GMWEATHER_CMB_SPENDTIME_NOW 1182
#define IDC_GMWEATHER_CMB_STARTDAY      1182
#define IDC_GMWEATHER_CHK1              1183
#define IDC_GMWEATHER_CHK2              1184
#define IDC_GMWEATHER_CHK3              1185
#define IDC_GMWEATHER_CMB_ENDDAY        1185
#define IDC_GMWEATHER_CMB_TYPE          1185
#define IDC_GMWEATHER_CHK4              1186
#define IDC_GMWEATHER_CHK_NOW           1187
#define IDC_GMWEATHER_CMB_CHANNEL       1188
#define IDC_GMWEATHER_BTN_NOW           1189
#define IDC_GMWEATHER_BTN_EXECUTION     1190
#define IDC_GMWEATHER_BTN_RETURN        1191
#define IDC_GMWEATHER_DATETIMEPICKER_START 1192
#define IDC_GMWEATHER_DATETIMEPICKER_END 1193
#define IDC_DATETIMEPICKER1             1194
#define IDC_GM_MAPCHANGE_HIDE_BTN_MAP   1195
#define IDC_GM_MAPCHANGE_HIDE_CMB_MAP   1196
#define IDC_GM_MAPCHANGE_HIDE_CMB_CHANNEL 1197
#define IDC_GM_MAPCHANGE_HIDE_BTN_ON    1198
#define IDC_GM_MAPCHANGE_HIDE_BTN_OFF   1199
#define IDC_GM_MAPCHANGE_HIDE_BTN_APPLY 1201
#define IDC_GM_MAPCHANGE_HIDE_BTN_CANCEL 1202
#define IDC_GMHIDE_CMB_CHANNEL          1203
#define IDC_RADIO1                      1204
#define IDC_GMREGEN_SCRIPT_RADIO        1204
#define IDC_GMMOVE_CHK_MINIMAP_ON       1204
#define IDC_GMITEM_EDIT_SEARCH          1205
#define IDC_GMMOVE_CHK_MINIMAP_OFF      1205
#define IDC_GMITEM_SEARCHFROM           1206
#define IDC_TSITEM_BTN_WEAPON           1210
#define IDC_TSITEM_CMB_WEAPON           1211
#define IDC_TSITEM_CMB_WEAPONGRADE      1212
#define IDC_TSITEM_BTN_CLOTHES          1213
#define IDC_TSITEM_CMB_CLOTHES          1214
#define IDC_TSITEM_CMB_CLOTHESGRADE     1215
#define IDC_TSITEM_BTN_ACCESSORY        1216
#define IDC_TSITEM_CMB_ACCESSORY        1217
#define IDC_TSITEM_BTN_SKILLBOOK        1218
#define IDC_TSITEM_CMB_SKILLBOOK        1219
#define IDC_TSITEM_BTN_POTION           1220
#define IDC_TSITEM_CMB_POTION           1221
#define IDC_TSITEM_EDT_POTION           1222
#define IDC_TSITEM_BTN_ETC              1223
#define IDC_TSITEM_CMB_ETC              1224
#define IDC_TSITEM_EDT_ETC              1225
#define IDC_TSITEM_BTN_MONEY            1226
#define IDC_TSITEM_EDT_MONEY            1227
#define IDC_TSITEM_BTN_SEARCH           1228
#define IDC_TSITEM_EDIT_SEARCH          1229
#define IDC_TSITEM_BTN_SKILL            1230
#define IDC_TSITEM_CMB_SKILL            1231
#define IDC_TSITEM_CMB_SKILLSUNG        1232
#define IDC_TSCHAR_CMB_GENDER           1232
#define IDC_TSITEM_BTN_ABILITY          1233
#define IDC_TSCHAR_CMB_JOB              1233
#define IDC_TSITEM_EDT_ABILITY          1234
#define IDC_TSCHAR_CMB_FACE             1234
#define IDC_TSITEM_BTN_GET              1235
#define IDC_TSCHAR_CMB_HAIR             1235
#define IDC_TSITEM_BTN_CANCEL           1236
#define IDC_TSITEM_SEARCHFROM           1237
#define IDC_TSITEM_SPN_POTION           1238
#define IDC_TSITEM_SPN_ETC              1239
#define IDC_TSCHAR_EDIT_HAIR            1241
#define IDC_TSCHAR_EDIT_FACE            1242
#define IDC_TSCHAR_CMB_RACE             1243
#define IDC_TSCHAR_BTN_APPLY            1244
#define IDC_TSCHAR_BTN_CANCEL           1245
#define IDC_TSMOVE_OK                   1246
#define IDC_TSMOVE_CANCEL               1247
#define IDC_TSMOVE_BTN_MAP              1248
#define IDC_TSMOVE_BTN_XY               1250
#define IDC_TSMOVE_CMB_MAP              1251
#define IDC_TSMOVE_EDT_X                1253
#define IDC_TSMOVE_EDT_Y                1254
#define IDC_TSREGEN_BTN_MODEDIRECT      1256
#define IDC_TSREGEN_CMB_MOBNAME         1257
#define IDC_TSREGEN_CMB_MAP             1258
#define IDC_TSREGEN_EDT_MOBNUM          1259
#define IDC_TSREGEN_EDT_RAD             1261
#define IDC_TSREGEN_EDT_ITEM            1262
#define IDC_TSREGEN_CMB_ITEM            1263
#define IDC_TSREGEN_EDT_X               1264
#define IDC_TSREGEN_EDT_Y               1265
#define IDC_TSREGEN_BTN_MYPOS           1266
#define IDC_TSREGEN_BTN_MODEFILE        1267
#define IDC_TSREGEN_BTN_OPEN            1268
#define IDC_TSREGEN_EDT_FILE            1269
#define IDC_TSREGEN_BTN_DELETE          1270
#define IDC_TSREGEN_BTN_APPLY           1271
#define IDC_TSREGEN_BTN_CANCEL          1272
#define IDC_COMBO1                      1273
#define IDC_TSITEM_CMB_TOSLOT           1273
#define IDC_GMITEM_SEARCH               1273
#define IDC_GMREGEN_VEHICLE_DROPDOWN    1274
#define IDC_GMDUNGEON_CMB_MAPLIST       1275
#define IDC_PROGRESS1                   1276
#define IDC_GMDUNGEON_LSB_DUNGEONLIST   1276
#define IDC_TSQUEST_BTN_TEST            1277
#define IDC_TSQUEST_LIST                1278
#define IDC_TSQUEST_BTN_CANCLE          1279
#define IDC_GMWEATHER_EDIT_INTENSITY    1280
#define IDC_GMWEATHER_BTN_SHOW_INFO     1281
#define IDC_GMWEATHER_BTN_HIDE_INFO     1282
#define IDC_TSWEATHER_BTN_MAP           1283
#define IDC_TSWEATHER_CMB_MAP           1284
#define IDC_TSWEATHER_CMB_TYPE          1285
#define IDC_TSWEATHER_EDIT_INTENSITY    1286
#define IDC_TSWEATHER_BTN_SHOW_INFO     1287
#define IDC_TSWEATHER_BTN_HIDE_INFO     1288
#define IDC_TSWEATHER_BTN_APPLY         1289
#define IDC_TSWEATHER_BTN_STOP          1290
#define IDC_GMREGEN_BTN_UNSUMMON_VEHICLE 1291
#define IDC_GMREGEN_VEHICLE_GET_BUTTON  1293
#define IDC_GMREGEN_SUMMON_MONSTER_CHECK 1294
#define IDC_GMREGEN_SUMMON_VEHICLE_CHECK 1295
#define IDC_GMDUNGEON_BTN_GETINFO       1296
#define IDC_SCRIPT_OBJECT_EDIT          1296
#define IDC_GMDUNGEON_BTN_GETDETAILINFO 1297
#define IDC_SCRIPT_OBJECT_FIND_BUTTON   1297
#define IDC_GMDUNGEON_BTN_MORNITORING   1298
#define IDC_BUTTON2                     1298
#define IDC_SCRIPT_FILE_OPEN_BUTTON     1298
#define IDC_GMDUNGEON_BTN_GETDETAILINFO2 1299
#define IDC_SCRIPT_FILE_EDIT            1299
#define IDC_GMCHAT_EDT_SEC              1299
#define IDC_GMDUNGEON_BTN_CLEARDETAILINFO 1300
#define IDC_GMDUNGEON_EDT_DETAILINFO    1301
#define IDC_TS_MNBTN_NONE               2001
#define IDC_TS_MNBTN_CHARACTOR          2002
#define IDC_TS_MNBTN_ITEM               2003
#define IDC_TS_MNBTN_ACTION             2004
#define IDC_TS_MNBTN_EFFECT             2005
#define IDC_TS_MNBTN_MOB                2006
#define IDC_TS_MNBTN_MOVE               2007
#define IDC_TS_MNBTN_QUEST              2008
#define IDC_TS_MNBTN_WEATHER            2009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40032
#define _APS_NEXT_CONTROL_VALUE         1301
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
